[move] Add error messages for linker error #9999
aptos-labs/aptos-core pull request #10054
Opened 2023-09-14 21:37 UTC by aalok-t

### Description

Add error messages for `LINKER_ERROR`, fixing https://github.com/aptos-labs/aptos-core/issues/9999 (part of https://github.com/aptos-labs/aptos-core/issues/9580)

2023-09-15 00:15 UTC, vineethk requested changes
Tests are failing:

```
error[E0599]: no method named `with_message` found for enum `StatusCode` in the current scope
   --> third_party/move/move-vm/runtime/src/unit_tests/vm_arguments_tests.rs:634:53
    |
634 |         assert_eq!(status, StatusCode::LINKER_ERROR.with_message(format!("Linker Error: Signature {:?} is deprecated", signature)));
    |                                                     ^^^^^^^^^^^^ method not found in `StatusCode`

error[E0599]: no method named `with_message` found for enum `StatusCode` in the current scope
   --> third_party/move/move-vm/runtime/src/unit_tests/vm_arguments_tests.rs:817:63
    |
817 |     assert_eq!(error.major_status(), StatusCode::LINKER_ERROR.with_message(format!("Linker Error: Call to item at a non-existent external module {:?}", module)));
    |                                                               ^^^^^^^^^^^^ method not found in `StatusCode`

For more information about this error, try `rustc --explain E0599`.
```

2023-09-15 17:12 UTC, brmataptos requested changes

2023-09-15 18:30 UTC, aalok-t commented on aptos-move/e2e-testsuite/src/tests/scripts.rs
> +    let module = Identifier::new("module").unwrap();
Yes, but that didn't work well so I decided against it. I will remove this line. Thanks Brain!

2023-09-15 20:18 UTC, brmataptos approved these changes

2023-09-15 22:44 UTC, vineethk reviewed
Minor comments to address. lgtm otherwise.

2023-09-15 22:44 UTC, vineethk commented on aptos-move/e2e-testsuite/src/tests/scripts.rs
>          //StatusCode::LINKER_ERROR
Remove comment, no longer useful.

2023-09-15 22:44 UTC, vineethk commented on third_party/move/move-binary-format/src/file_format.rs
>              // TODO we might want a more informative error here
Perhaps this change addresses this TODO, so remove comment?

2023-09-18 19:54 UTC, vineethk approved these changes

2023-09-21 17:56 UTC, merged