[SDKv2] Add secp256k1 account authenticator
aptos-labs/aptos-core pull request #10410
Opened 2023-10-05 07:13 UTC by 0xjinn

### Description

Adds the AccountAuthenticator for secp256k1

### Test Plan

pnpm fmt & pnpm test

2023-10-05 07:13 UTC, 0xjinn commented
Current dependencies on/for this PR:
* main
  * **PR #10410** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/10410" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/aptos-labs/aptos-core/10410?utm_source=stack-comment).

2023-10-05 18:28 UTC, xbtmatt commented on ecosystem/typescript/sdk_v2/src/transactions/authenticator/account.ts
> +   * Transaction authenticator Secp256k1 for a single signer transaction
```suggestion
   * A Secp256k1 AccountAuthenticator for a single signer
```

or something like this- technically this isn't the `TransactionAuthenticator`, it's the `AccountAuthenticator`

2023-10-05 18:29 UTC, xbtmatt commented on ecosystem/typescript/sdk_v2/src/transactions/authenticator/account.ts
> +   * @param public_key Account's Secp256k1 public key.
```suggestion
   * @param public_key A Secp256k1 public key
```

2023-10-05 18:29 UTC, xbtmatt commented on ecosystem/typescript/sdk_v2/src/transactions/authenticator/account.ts
> +   * @param signature Account's Secp256k1 signature
```suggestion
   * @param signature A Secp256k1 signature
```

2023-10-05 18:30 UTC, xbtmatt requested changes
Need to add this to the `AccountAuthenticator` `deserialize` function, other than that looks good

```typescript
      case AccountAuthenticatorVariant.AccountAuthenticatorSecp256k1:
        return AccountAuthenticatorSecp256k1.load(deserializer);
```

2023-10-05 18:33 UTC, 0xjinn commented
> Need to add this to the `AccountAuthenticator` `deserialize` function, other than that looks good
> 
> ```ts
>       case AccountAuthenticatorVariant.AccountAuthenticatorSecp256k1:
>         return AccountAuthenticatorSecp256k1.load(deserializer);
> ```

Ah good catch!

2023-10-05 20:56 UTC, 0xmaayan commented on ecosystem/typescript/sdk_v2/src/types/index.ts
> +  AccountAuthenticatorSecp256k1 = 2,
lets shorten these?
```
export enum AccountAuthenticatorVariant {
  Ed25519 = 0,
  MultiEd25519 = 1,
  Secp256k1 = 2,
}
```

2023-10-05 21:35 UTC, 0xmaayan commented on ecosystem/typescript/sdk_v2/src/transactions/authenticator/account.ts
> +export class AccountAuthenticatorSecp256k1 extends AccountAuthenticator {
need to add to the main `AccountAuthenticator` class https://github.com/aptos-labs/aptos-core/blob/main/ecosystem/typescript/sdk_v2/src/transactions/authenticator/account.ts#L11

2023-10-06 03:15 UTC, xbtmatt approved these changes
LGTM!

2023-10-06 03:50 UTC, 0xmaayan approved these changes

2023-10-06 07:42 UTC, merged