Fix issue 10468
aptos-labs/aptos-core pull request #10526
Opened 2023-10-16 20:58 UTC by fEst1ck

### Description
Move unit tests continue to run in the presence of compiler warnings, but the warnings are shown.
### Test Plan
Existing tests.

2023-10-16 21:14 UTC, brmataptos commented on third_party/move/move-compiler/src/diagnostics/mod.rs
> +pub fn report_diagnostics_maynot_exit(files: &FilesSourceText, diags: Diagnostics) {
Naming this `report_diagnostics_exit_on_error` might be better.

2023-10-16 21:36 UTC, brmataptos commented
Please test by running aptos-framework tests with environment variables MOVE_COMPILER_WARN_OF_DEPRECATION_USE=1 and WARN_OF_DEPRECATION_USE_IN_APTOS_LIBS=1
set, as this will trigger warnings building aptos libs.

2023-10-16 21:40 UTC, fEst1ck commented
> Please test by running aptos-framework tests with environment variables MOVE_COMPILER_WARN_OF_DEPRECATION_USE=1 and WARN_OF_DEPRECATION_USE_IN_APTOS_LIBS=1 set, as this will trigger warnings building aptos libs.

Yes, I did.

2023-10-16 22:12 UTC, brmataptos approved these changes

2023-10-17 13:37 UTC, gregnazario approved these changes

2023-10-17 13:39 UTC, gregnazario commented
Please change the commit message to match the contributing guidelines.

Something like:
[compiler] Allow unit testing with warnings

2023-10-17 13:40 UTC, gregnazario requested changes
Can we additionally add a direct unit test for this with the CLI so it doesn't regress?

2023-10-19 23:02 UTC, wrwg reviewed
Nice. As @gregnazario suggested, please add a unit test

2023-11-14 18:44 UTC, brmataptos commented
@gregnazario @wrwg this seems hard to write a test for, since the problem only shows up if the warning is in the stdlib (not an explicit dependency).  We'd have to add a lot of mechanism to inject a warning into warning code.  Perhaps Zekun can merge it without a test?

2023-11-14 18:59 UTC, gregnazario commented
> @gregnazario @wrwg this seems hard to write a test for, since the problem only shows up if the warning is in the stdlib (not an explicit dependency).  We'd have to add a lot of mechanism to inject a warning into warning code.  Perhaps Zekun can merge it without a test?

Does this not also happen if you have a warning in your test?

2023-11-14 20:01 UTC, brmataptos commented
> > @gregnazario @wrwg this seems hard to write a test for, since the problem only shows up if the warning is in the stdlib (not an explicit dependency).  We'd have to add a lot of mechanism to inject a warning into warning code.  Perhaps Zekun can merge it without a test?
> 
> Does this not also happen if you have a warning in your test?

No.  The flow is special for the stdlib.  That's the problem.

2023-11-15 05:18 UTC, gregnazario approved these changes

2023-11-16 03:19 UTC, merged