add CommitMessage::Nack
aptos-labs/aptos-core pull request #11711
Opened 2024-01-19 18:55 UTC by brianolson

### Description

add CommitMessage::Nack to reply to ::Vote and ::Decision that don't get ::Ack

The real win is that the server doesn't leave RPCs hanging to timeout. Timeout error counters and log messages will be less spammy.

### Test Plan

existing tests

2024-01-19 19:17 UTC, zekun000 reviewed
we need to match the message type here now to only accept Ack 
https://github.com/aptos-labs/aptos-core/blob/d6e5e1987a8b711e3bfd8cde31cb98782f34938e/consensus/src/pipeline/commit_reliable_broadcast.rs#L58

2024-01-22 19:57 UTC, zekun000 approved these changes

2024-01-22 19:57 UTC, zekun000 commented on consensus/src/pipeline/commit_reliable_broadcast.rs
> +        match ack {
nit: I'd just write it like this
```
  ensure!(matches!(ack, CommitMessage::Ack(_), "Unexpected ack");
```

2024-01-22 22:10 UTC, JoshLind approved these changes
Looks reasonable to me. Only comment is that we'll need to be aware of the rollout, i.e., we should expect that some nodes won't be able to parse the "nack" during the rollout of the next release. But, AFAICT, that should be okay? 😄

2024-01-22 22:15 UTC, brianolson commented
If a node waiting for the RPC that would have timed out instead errors on that RPC because it gets a Nack, either way it's an RPC failing (harmlessly)
Although the policy _I wish we had_ would be that an unexpected message should be a drop-connection offense.

2024-01-23 17:53 UTC, zekun000 requested changes
hmm, I think @JoshLind had a good point, because we don't differentiate the message types before the sender will take nack as ack and stop broadcasting the values.

we need to first make the change on the message handling in one release then adding nack in next release

2024-01-23 17:54 UTC, zekun000 commented
ah nvm, it won't be able to parse the nack

2024-01-23 17:54 UTC, zekun000 approved these changes

2024-01-29 14:41 UTC, merged