[NFT Metadata Crawler] Enable better quality from configs + add IPFS gateway auth
aptos-labs/aptos-core pull request #11801
Opened 2024-01-26 21:33 UTC by just-in-chang

### Description
Add more options for image quality to config and pinata auth for IPFS requests. 

### Test Plan
Tested locally + existing unit tests

2024-01-26 21:39 UTC, larry-aptos approved these changes

2024-01-26 22:22 UTC, banool requested changes

2024-01-26 22:22 UTC, banool commented on ecosystem/nft-metadata-crawler-parser/src/utils/constants.rs
> +pub const DEFAULT_MAX_FILE_SIZE_BYTES: u32 = 5_000_000;
This is just a default ofc but in prod we should probs set this to like 10-15mb instead.

2024-01-26 22:22 UTC, banool commented on ecosystem/nft-metadata-crawler-parser/src/worker.rs
> +    pub ipfs_auth: Option<String>,
Feels weird that the config has to pass in `?token=<key>`, can we just accept the key and then format the URL in the code accordingly?

2024-01-27 04:17 UTC, banool approved these changes

2024-01-29 04:11 UTC, merged