[framework] add methods to create additional mint/burn capabilities
aptos-labs/aptos-core pull request #1228
Opened 2022-06-02 08:15 UTC by mkurnikov

## Motivation

It's needed to allow minting coins from the multiple places. 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

I've added a test that invokes the new functionality.

2022-06-02 18:56 UTC, movekevin reviewed
There's a potential design consideration here: Should creating a coin with multiple minters/burns be done with the Coin module, or should be it be a wrapper module such as ManagedCoin? The trade off here is complexity vs functionality - if we keep adding more functionalities, Coin can quickly become very complex.

2022-06-02 18:56 UTC, movekevin commented on aptos-move/framework/aptos-framework/sources/Coin.move
> +    public fun add_extra_mint_capability<CoinType>(_cap: &MintCapability<CoinType>): MintCapability<CoinType> {
nit: May be name this create_mint_capability()?

2022-06-02 18:56 UTC, movekevin commented on aptos-move/framework/aptos-framework/sources/Coin.move
If we're adding ways to create mint/burn caps, we should probably add ways to destroy them as well (they're not droppable).

2022-06-02 22:39 UTC, borispovod commented
> There's a potential design consideration here: Should creating a coin with multiple minters/burns be done with the Coin module, or should be it be a wrapper module such as ManagedCoin? The trade off here is complexity vs functionality - if we keep adding more functionalities, Coin can quickly become very complex.

There are several options on how we can design it IMHO. Theoretically, we can get a rid from many mint/burn abilities and use only friends functions in new deployed modules contains coin generic type, while the devs would store mint/burn cap indeed under their accounts, yet in my opinion it's still breaking language design and makes it hard to correctly work with Move (because caps should be stored somewhere, usually it's coin dev address, and there should be option to extract caps when some friend module calling mint/burn functions, it seems brakes Move logic a little, because you will have to hardcore address where caps stored in the code, not sure it's good design). 

So i think option with many capabilities could an option (in the same time i still think we should do something with `Coin::initialize` and get rid of `Reflect` there).

2022-06-06 04:41 UTC, davidiw commented
@borispovod 

> So i think option with many capabilities could an option (in the same time i still think we should do something with `Coin::initialize` and get rid of `Reflect` there).

Could you elaborate? Is this about TypeInfo?

2022-06-06 04:43 UTC, davidiw requested changes
These capabilities are already copy. I think there's a better solution in what we already have in the Capability.move from the standard library, but I think there are a lot of nuances here... Should a capability be copy, should it allow further delegation, and how do you protect it from misuse.

I'm not sure what this PR is adding.

2022-06-07 11:57 UTC, borispovod commented
> @borispovod
> 
> > So i think option with many capabilities could an option (in the same time i still think we should do something with `Coin::initialize` and get rid of `Reflect` there).
> 
> Could you elaborate? Is this about TypeInfo?

Yeah, let's talk in our chat. I will explain what i mean.

Regarding the current PR, it's my mistake, i totally forgot about copy ability as it's not very popular approach :) 

@mkurnikov can you close the current PR?

2022-06-07 11:57 UTC, closed without merging