convert UnknownAttribute from a warning into an error
aptos-labs/aptos-core pull request #12857
Opened 2024-04-11 22:23 UTC by brmataptos

[1;95;0c## Description

Convert "Unknown attribute" warning into an error.

Fixes #9411

## Type of Change
- [ ] New feature
- [X] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [X] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [ ] Other (specify)

## How Has This Been Tested?
Usual tests.  Warnings have been deployed and tested for a while.  This just turns it into an error.

## Key Areas to Review
Consider security issues versus user convenience (notably, partners who use their own attributes for some reason).
Note that those using their own attributes are probably customizing the code and can disable this.

## Checklist
- [X] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I identified and added all stakeholders and component owners affected by this change as reviewers
- [X] I tested both happy and unhappy path of the functionality
- [X] I have made corresponding changes to the functionalitydocumentation

2024-04-11 22:38 UTC, gedigi approved these changes

2024-04-11 22:46 UTC, GotenJBZ approved these changes

2024-04-12 22:59 UTC, davidiw requested changes
What is the default in the CLI? If it is to not skip, then I recommend we actually make this skip. This will likely break a lot of CICD and tools in the community as their are attributes outside of those used by the compiler. Why not make this an opt-in model rather than opt-out?

Requesting changes until this is resolved, especially since we have sufficient approvals to land.

2024-04-12 23:08 UTC, gedigi commented
do these attributes not used by the compiler have any actual purpose or change the behavior of the code?

2024-04-12 23:14 UTC, davidiw commented
Here's an example: https://github.com/hippospace/move-to-ts

2024-04-13 03:38 UTC, brmataptos commented
> Here's an example: https://github.com/hippospace/move-to-ts

Thanks.  This is useful to see.

2024-10-27 02:05 UTC, closed without merging