1.11 release yaml fix
aptos-labs/aptos-core pull request #12900
Opened 2024-04-15 23:26 UTC by zjma

## Description
Before 1.11 framework upgrade, we should use the `DefaulGasWithOverrideOld` entry.

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [ ] Other (specify)

## How Has This Been Tested?

## Key Areas to Review

## Checklist
- [ ] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I identified and added all stakeholders and component owners affected by this change as reviewers
- [ ] I tested both happy and unhappy path of the functionality
- [ ] I have made corresponding changes to the documentation

2024-04-15 23:40 UTC, vgao1996 requested changes
Need to remove "feature_version: 13" from step 2 too

2024-04-15 23:43 UTC, vgao1996 approved these changes

2024-04-15 23:44 UTC, sherry-x approved these changes

2024-04-15 23:45 UTC, vgao1996 approved these changes

2024-04-16 01:24 UTC, zjma commented on aptos-move/aptos-release-builder/data/release.yaml
> +      - RawScript: aptos-move/aptos-release-builder/data/proposals/randomness_framework_initialization.move
bookmark

2024-04-16 03:13 UTC, zjma commented on aptos-move/aptos-release-builder/data/release.yaml
> +      - RawScript: aptos-move/aptos-release-builder/data/proposals/randomness_framework_initialization.move
@sherry-x double-checking it is fine to have the initialization

2024-04-16 03:50 UTC, merged