Change JWT field parsing logic so that there is a "quoted" path and an "unquoted" path
aptos-labs/aptos-core pull request #13036
Opened 2024-04-25 19:10 UTC by rex1fernando

# Summary

## The Issue

Previously, there was a single template `JWTFieldCheck` which handled parsing of JWT fields with both quoted values (i.e., strings) and unquoted values (i.e., numbers, booleans). Because this one templated generically handled both cases, it was more permissive than it needed to be. Two examples of this:

* The circuit would accept fields with string values that didn't have and end quote. For instance: `"key": "value,` could be parsed as `key` mapping to `value`. This also allowed fields with commas such as  `"key": "value1,value2",` to be maliciously parsed as`key` mapping to `value1`.
* More specifically, `JWTFieldCheck` handled both quoted and unquoted values by simply not constraining the characters before and after the value at all. So it was possible to put any character directly before and after a value, e.g., `"key": xvaluey,` could also be parsed as `key` mapping to `value`.

## The Fix

#

2024-04-25 20:43 UTC, mstraka100 commented on keyless/circuit-data/templates/mainTemplate.circom
> +    ParseJWTFieldWithUnquotedValue(maxEVKVPairLen, maxEVNameLen, maxEVValueLen)(ev_field, ev_name, ev_value, ev_field_len, ev_name_len, ev_value_index, ev_value_len, ev_colon_index);
There appear to be some providers as of a few years ago that incorrectly use strings for email_verified: https://community.auth0.com/t/userinfo-email-verified-field-string-boolean-or-both/27553

2024-04-25 21:05 UTC, mstraka100 commented on keyless/circuit-data/templates/helpers/jwt_field_parsing.circom
> +    signal value_first_quote <== SelectArrayValue(maxKVPairLen)(field, value_index-1);
This would be cleaner if we called `ParseJWTFieldWithUnquotedValue` here and then added the quote value checking logic on top of it

2024-04-25 21:08 UTC, mstraka100 commented on keyless/circuit-data/templates/mainTemplate.circom
> +    ParseJWTFieldWithUnquotedValue(maxEVKVPairLen, maxEVNameLen, maxEVValueLen)(ev_field, ev_name, ev_value, ev_field_len, ev_name_len, ev_value_index, ev_value_len, ev_colon_index);
This might actually be fine, since `ParseJWTFieldWithUnquotedValue` seems to allow for quoted values as well

2024-04-25 21:09 UTC, mstraka100 commented on keyless/circuit-data/templates/mainTemplate.circom
> +    log("aud");
Remove these log statements? I don't see any use for them

2024-04-25 21:09 UTC, mstraka100 commented on keyless/circuit-data/templates/mainTemplate.circom
> +    log("uid");
Remove

2024-04-25 21:09 UTC, mstraka100 commented on keyless/circuit-data/templates/mainTemplate.circom
> +    log("iss");
Remove

2024-04-25 21:09 UTC, mstraka100 commented on keyless/circuit-data/templates/mainTemplate.circom
> +    log("iat");
Remove

2024-04-25 21:10 UTC, mstraka100 commented on keyless/circuit-data/templates/mainTemplate.circom
> +    log("nonce");
Remove

2024-04-25 22:12 UTC, mstraka100 requested changes
Per our most recent discussion, we should have a third path for `email_verified` that allows for both quoted and unquoted values

2024-04-26 05:33 UTC, rex1fernando commented
> Per our most recent discussion, we should have a third path for `email_verified` that allows for both quoted and unquoted values

Will make a separate PR for this.

2024-04-26 05:33 UTC, merged