Implement secp256k1 recovery native function
aptos-labs/aptos-core pull request #1305
Opened 2022-06-08 15:02 UTC by hendrikhofstadt

## Motivation

Verifying secp256k1 will help create compatibility with the EVM world. E.g. this will allow 0x style signed orders to be compatible, existing bridges to adapt quicker and GSN style services to reuse infrastructure.

libsecp256k1 is pure rust, widely adopted and well tested.

Open for a discussion on gas pricing for this.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md#pull-requests)?

CLA pending

## Test Plan

Tests written in Move

2022-06-09 02:22 UTC, davidiw reviewed
This is an amazing contribution. I greatly appreciate the steps you went through to build this. It isn't super clear to me exactly how this would be used. Granted I may not be as deep into the context that you provided. Could you help work out a clearer and more concrete application model?

2022-06-09 08:32 UTC, hendrikhofstadt commented
The immediate motivation is that this will be required for an integration of Wormhole (Interoperability protocol).
Wormhole uses a ECDSA multisig on the secp256k1 curve only.

ECDSA on secp256k1 is the main schema and curve for ETH based chains. The `ecrecover` precompile/native in ETH is used by most developers for signature verification (by recovering the signer key) and has thus made it into most non-EVM execution layers as well (e.g. Solana, NEAR). For most protocols this curve is the lowest common denominator and they are used to the `ecrecover` as primary operation.
This native is a more low-level implementation of the public key recovery. ecrecover additionally hashes (keccak/sha3 256) the key and truncates the result (thereby deriving the ethereum address). This can be achieved in a higher level function since afaik sha3 is already supported as builtin.

Adopting this will make it easier for existing protocols to expand into aptos, developers to have a smoother transition finding well known primitives and bridges to adopt aptos without requiring them to switch to eddsa.

Other prominent examples of protocols that heavily rely on this are 0x (ecdsa signed limit orders) and Chainlink (oracle prices are signed using ecdsa)

2022-06-09 18:03 UTC, alinush commented on aptos-move/framework/aptos-framework/sources/Signature.move
> +    fun test_secp256k1() {
Can we add a randomized test here: 

- pick a random key-pair, 
- pick and sign a random message, 
- call recover
- check it returns the PK.

2022-06-10 19:02 UTC, alinush commented on aptos-move/framework/aptos-framework/sources/Signature.move
> +    fun test_secp256k1() {
...otherwise, it looks good.

2022-06-13 22:05 UTC, alinush requested changes
Can we add a randomized test case to `test_secp256k1` (see comments)?

2022-07-19 15:41 UTC, merged