[aptos-framework] token bucket
aptos-labs/aptos-core pull request #15114
Opened 2024-10-30 00:26 UTC by lightmark

token bucket for rate limiting.

2025-01-08 22:10 UTC, igor-aptos requested changes

2025-01-08 22:10 UTC, igor-aptos commented on aptos-move/framework/aptos-framework/sources/account_abstraction/permissioned_delegation.move
> +        max_txn_per_minute: Option<u64>,
maybe just accept directly Option<RateLimiter>, as you might want to have different configurations for the RateLimiter (i.e. 10 txns / minute, vs 100 txns/day, or later potentially different RateLimiter variants).

2025-01-08 22:10 UTC, igor-aptos commented on aptos-move/framework/aptos-framework/sources/account_abstraction/permissioned_delegation.move
> +        let pubkey = ed25519::new_unvalidated_public_key_from_bytes(key);
do we want this to be tied to ed25519, or potentially delegated to another account - whose authentication we then use instead?

2025-01-08 22:10 UTC, igor-aptos commented on aptos-move/framework/aptos-framework/sources/account_abstraction/permissioned_delegation.move
> +    enum HandleBundle has store {
don't like the term "bundle", every struct is a bundle.

maybe `DelegationHandle`, `AccountDelegation` or something like that.

2025-01-08 22:10 UTC, igor-aptos commented on aptos-move/framework/aptos-framework/sources/account_abstraction/permissioned_delegation.move
> +    struct Delegation has key {
maybe RegisteredDelegations or something to refer to this being a collection?

2025-01-08 22:10 UTC, igor-aptos commented on aptos-move/framework/aptos-framework/sources/account_abstraction/permissioned_delegation.move
> +        handle_bundles: Table<ed25519::UnvalidatedPublicKey, HandleBundle>
hm should we be using public_key here, or authentication_key (i.e. what we use as account address) - the later seems more intuitive to me.

2025-01-13 04:54 UTC, lightmark commented on aptos-move/framework/aptos-framework/sources/account_abstraction/permissioned_delegation.move
> +        handle_bundles: Table<ed25519::UnvalidatedPublicKey, HandleBundle>
here the authentication is made through a ed25519 key pair, which has nothing to do with aptos account. we can do the authentication_key version, which require the whole signing scheme, authentication_key, public key, signing method (multisig, single_key and which cryptographic algorithm... which is way more complicated)

2025-01-13 19:18 UTC, igor-aptos commented on aptos-move/framework/aptos-framework/sources/account_abstraction/permissioned_delegation.move
> +        handle_bundles: Table<ed25519::UnvalidatedPublicKey, HandleBundle>
maybe to make this potentially expandable later, change the key here to :

```
enum HandleKey {
   Ed25519PublicKey(ed25519::UnvalidatedPublicKey)
 }
```

so that you have 
handle_bundles: Table<HandleKey, HandleBundle>

you can then also change add_permissioned_handle to receive HandleKey instead of bytes?

2025-01-15 00:09 UTC, igor-aptos requested changes

2025-01-15 00:09 UTC, igor-aptos commented on aptos-move/framework/aptos-framework/sources/account/rate_limiter.move
> +            limiter.last_refill_timestamp = current_time;
this needs to be outside of `if (new_tokens > 0)`, as you are updating fractional_accumulated below.

2025-01-16 01:49 UTC, lightmark commented on aptos-move/framework/aptos-framework/sources/account/permissioned_delegation.move
> +    enum DelegationKey has copy, drop {
did that in the nex tpr

2025-01-16 20:31 UTC, runtian-zhou approved these changes
Stamp to unblock.

2025-01-16 20:31 UTC, runtian-zhou commented on aptos-move/framework/aptos-framework/sources/account/rate_limiter.move
> +        limiter.fractional_accumulated = accumulated_amount % limiter.refill_interval;
When rate limiter exceeds capacity, will the remainder added to this fractional_accumulated?

2025-01-16 20:59 UTC, lightmark commented on aptos-move/framework/aptos-framework/sources/account/rate_limiter.move
> +        limiter.fractional_accumulated = accumulated_amount % limiter.refill_interval;
good point.
if limiter.current_amount + new_tokens < limiter.capacity, we 
`limiter.fractional_accumulated = accumulated_amount % limiter.refill_interval;`
otherwise it should be 0
cc: @igor-aptos

2025-01-17 07:22 UTC, lightmark commented on aptos-move/framework/aptos-framework/sources/account/rate_limiter.move
> -        limiter.current_amount = limiter.current_amount + new_tokens;
I found this line and slap myself.

2025-01-17 19:05 UTC, merged