[sdk-doc] Doc for SDK overview and SDK validation
aptos-labs/aptos-core pull request #1517
Opened 2022-06-21 02:07 UTC by jjleng

### Description
Doc for SDK overview. It explains the layers and components for Aptos SDKs. The doc also presents the test vector validation method we used to validate our SDKs. 

### Test Plan
Previewed locally

2022-06-22 16:24 UTC, rajkaramchedu commented on developer-docs-site/docs/sdks/sdk-overview.md
> +:::
Inserting a new line after `:::notice` and above `:::` will fix the rendering.

2022-06-22 16:27 UTC, rajkaramchedu commented on developer-docs-site/docs/sdks/sdk-overview.md
> +
On links, like 107 and 109 and everywhere else, always put a period either after "here" like `[here.]` or after the closing parenthesis of the url, like `.../bcs/serializer.test.ts).`

2022-06-22 16:37 UTC, rajkaramchedu commented
On the categorization and the filename. In the new docs category SDK, I am anticipating that in addition to the TS SDK, we will also have Python and Rust SDKs, at some point. So we can:

1. Write the SDK overview doc as a general document, as we have it now. This doc now only contains TS SDK details but we can add overview sections for Python and Rust into this same overview doc. In this case, the title Aptos SDK is correct.
2. Or, we can make this overview doc specific to TS only, hence make the filename as `ts-sdk-overview`, change the title to Typescript SDK. I've been thinking about this and I like this second option better. It keeps the docs specific and limited only to the scope of the title and filename. What do you think, @jjleng?

2022-06-22 18:32 UTC, jjleng commented
> 

Right now, we only have TS SDK fully maintained. Python SDK is partially maintained. To not make things too complicated, can we do option 1 for now? We can definitely split the doc later if needed.

2022-06-22 18:34 UTC, rajkaramchedu commented
> > 
> 
> Right now, we only have TS SDK fully maintained. Python SDK is partially maintained. To not make things too complicated, can we do option 1 for now? We can definitely split the doc later if needed.

Yes. Thanks.

2022-07-14 05:16 UTC, davidiw requested changes
not sure what happened here, this isn't a reviewable PR and its been here for a while... gonna close it out and leave it to you to resurrect.

2022-07-14 05:16 UTC, davidiw commented on developer-docs-site/docs/sdks/sdk-overview.md
> +2. The second level of validation is fuzzing tests with test vectors. The test vectors are produced by the same code used by the Aptos Blockchain. The test vectors are arrays of JSON objects. Each JS
fuzzing? I think it is more ensuring consistency with test vectors

2022-07-14 05:16 UTC, davidiw commented on developer-docs-site/docs/sdks/sdk-overview.md
> +See how Typescript SDK does vector validation [here](https://github.com/aptos-labs/aptos-core/pull/1461).
probably good to point to a specific commit not a PR

2022-07-14 05:16 UTC, closed without merging