aptos-framework repo migration: move-examples [1/n]
aptos-labs/aptos-core pull request #15208
Opened 2024-11-06 09:56 UTC by vgao1996

This migrates the move examples to use dependencies from the newly-setup aptos-framework repo.

2024-11-06 17:59 UTC, ziaptos approved these changes

2024-11-06 17:59 UTC, ziaptos commented on aptos-move/move-examples/drand/Move.toml
> +#AptosStdlib = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-stdlib", rev = "mainnet" }
why not just remove?

2024-11-06 18:00 UTC, fEst1ck approved these changes

2024-11-06 18:09 UTC, gregnazario requested changes

2024-11-06 18:09 UTC, gregnazario commented on aptos-move/move-examples/argument_example/Move.toml
> +AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "mainnet" }
These are purposely using the local framework so that they match in CI

2024-11-06 22:24 UTC, merged

2024-11-15 16:51 UTC, vineethk commented on aptos-move/move-examples/bonding_curve_launchpad/Move.toml
> -git = "https://github.com/aptos-labs/aptos-core.git"
@vgao1996 `aptos-move` subdir is not part of `"https://github.com/aptos-labs/aptos-framework.git"`, so this no longer works.