Aptos - Account Abstraction
aptos-labs/aptos-core pull request #15219
Opened 2024-11-06 23:43 UTC by lightmark

## Description
```
module aptos_framework::signing_data {
    enum SigningData has copy, drop {
        V1 { digest: vector<u8>, authenticator: vector<u8> },
    }

    #[test_only]
    public fun create_signing_data(digest: vector<u8>): SigningData {
        SigningData::V1 { digest }
    }

    public fun digest(signing_data: &SigningData): &vector<u8> {
        &signing_data.digest
    }

    public fun authenticator(signing_data: &SigningData): &vector<u8> {
        &signing_data.authenticator
    }
}
```
a function with the following signature can be used to authorize account..
```
/// The native function to dispatch customized move authentication function.
 native fun dispatchable_authenticate(
        account: signer,
        signing_data: SigningData,
        function: &FunctionInfo
    ): signer;
```

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [ ] Other (specify)

## How Has This Been Tested?

## Key Areas to Review
lite_account.move
signing_data.move
aptos_vm.rs

2024-11-22 22:53 UTC, igor-aptos reviewed
should we assert that signer AA returns is for the same account (i.e. account addresses match), to potentially avoid some class of problems

2024-11-22 22:55 UTC, igor-aptos commented on aptos-move/framework/aptos-framework/sources/lite_account.move
> +    struct DispatchableAuthenticator has key, copy, drop {
let's make this an enum?

2024-11-22 22:56 UTC, lightmark commented on aptos-move/framework/aptos-framework/sources/lite_account.move
> +    struct DispatchableAuthenticator has key, copy, drop {
Can enum have `key`?

2024-11-22 22:56 UTC, igor-aptos commented on aptos-move/framework/aptos-framework/sources/lite_account.move
> +    struct DispatchableAuthenticator has key, copy, drop {
sure, why not

2024-12-12 15:15 UTC, runtian-zhou reviewed
I'm a bit concerned over the changes in the transaction validation. There's a bunch of code reordering and I think we need to reason about the changes there very carefully...

2024-12-12 20:31 UTC, lightmark commented on types/src/transaction/mod.rs
> +                AccountAddress::ZERO,
look at the authenticator logic.

2024-12-12 20:34 UTC, lightmark commented on aptos-move/framework/aptos-framework/sources/coin.move
> +        account: &signer,
the 2nd commit.
We need this for updating permissions.

2024-12-12 20:35 UTC, lightmark commented on aptos-move/framework/aptos-framework/sources/aptos_account.move
> +        account: &signer,
for permission

2024-12-15 00:42 UTC, lightmark commented on aptos-move/framework/src/natives/function_info.rs
> +        if !module.address().is_special()
why we don't allow user functions?

2025-01-13 22:10 UTC, igor-aptos commented on aptos-move/framework/aptos-framework/sources/lite_account.move
> +module aptos_framework::lite_account {
maybe we should have accounts folder, and have this in there - and name it `move_authenticator.move`, 'dispatchable_authenticator.move' or `account_abstraction.move` (maybe move account.move to that folder too)

nothing in this PR needs to use term "lite", and actual "lite" structs should probably go to separate file anyways - they will just be stored at the same address.

2025-01-13 22:12 UTC, lightmark commented on aptos-move/framework/aptos-framework/sources/lite_account.move
> +module aptos_framework::lite_account {
kk. doing that now.

2025-01-14 00:03 UTC, lightmark commented on api/src/accounts.rs
> +        // self.verify_account_or_object_resource()?;
the demo wanna to read all the resources under a handle address but it is neither an account or object.

2025-01-15 19:34 UTC, igor-aptos commented on aptos-move/aptos-vm/src/transaction_validation.rs
> +                        .expect("fee_payer signer must exist"),
Can this ever happen? If so - i.e. on bad user input - expect will crash the node, while returning error VMStatus will abort/discard transaction.

probably safer to return error VMStatus - as even if this is invariant, you depend on a lot of callers passing in correct signers for this not to crash


on the other hand, things like:
```
MoveValue::U64(txn_sequence_number)
                        .simple_serialize()
                        .unwrap(),
```
are fine as you can easily validate it will never crash.

2025-01-15 19:34 UTC, igor-aptos commented on aptos-move/framework/aptos-framework/sources/account/account_abstraction.move
> +        V1 { auth_functions: OrderedMap<FunctionInfo, bool> }
how many different authenticators can be registered? 
is this guaranteed to never exceed a single storage slot? if not, maybe we should use BigOrderedMap?

on the other hand , limiting that to the single storage slot size might be a fine restriction

2025-01-15 19:34 UTC, igor-aptos commented on aptos-move/framework/aptos-framework/sources/account/account_abstraction.move
> +                    !ordered_map::contains(current_map, &auth_function),
you can use move2 syntax now :) 
`current_map.contains(&auth_function)`

2025-01-15 19:34 UTC, igor-aptos commented on aptos-move/framework/aptos-framework/sources/account/bcs_stream.move
> +module aptos_framework::bcs_stream {
what is this used for - I don't see any references to it?

2025-01-15 19:34 UTC, igor-aptos commented on aptos-move/framework/aptos-framework/sources/aptos_account.move
> +        account: &signer,
if I look at the other PR correctly - #15232, this is no longer needed, as check is in the prologue/epilogue function itself?

2025-01-15 19:34 UTC, igor-aptos commented on aptos-move/framework/aptos-framework/sources/transaction_validation.spec.move
> +        txn_sender_public_key: vector<u8>,
?

2025-01-15 19:34 UTC, igor-aptos commented on aptos-move/framework/aptos-framework/sources/transaction_validation.spec.move
> +        // };
?

2025-01-15 19:34 UTC, igor-aptos commented on aptos-move/framework/src/natives/account_abstraction.rs
> +    // Use Error to instruct the VM to perform a function call dispatch.
:O

2025-01-15 20:08 UTC, lightmark commented on aptos-move/framework/aptos-framework/sources/account/bcs_stream.move
> +module aptos_framework::bcs_stream {
this is used by permissioned delegation code in the next PR. @vgao1996 created this.

2025-01-15 20:19 UTC, lightmark commented on aptos-move/framework/aptos-framework/sources/account/account_abstraction.move
> +        V1 { auth_functions: OrderedMap<FunctionInfo, bool> }
that's something I am not sure. I cannot imagine an account needs so many slots. since this is an enum we can do that as V2 if necessary?

2025-01-15 20:21 UTC, igor-aptos commented on aptos-move/framework/aptos-framework/sources/account/account_abstraction.move
> +        V1 { auth_functions: OrderedMap<FunctionInfo, bool> }
yeah, fine with that, that makes sense

2025-01-15 20:33 UTC, lightmark commented on aptos-move/framework/aptos-framework/sources/aptos_account.move
> +        account: &signer,
oh, good point

2025-01-15 20:42 UTC, lightmark commented on aptos-move/framework/aptos-framework/sources/transaction_validation.spec.move
> +        txn_sender_public_key: vector<u8>,
weird indentation from ide, let me indent them all...

2025-01-16 00:07 UTC, vgao1996 requested changes
Done looking at the VM part.

There seems to be an issue with the handling of gas: what if `max_gg_gas` is higher than the `max_gas_amount` the transaction specifies?

2025-01-16 00:07 UTC, vgao1996 commented on aptos-move/aptos-vm/src/aptos_vm.rs
> +            max_aa_gas,
Same, what if `max_aa_gas` is higher than the txn's `max_gas_amount`?

2025-01-16 00:07 UTC, vgao1996 commented on aptos-move/aptos-gas-meter/src/algebra.rs
> +        self.initial_balance = reset_initial_balance_to
Yeah feel like it would be safer to have an interface `fn inject_balance()` rather than the current one that tries to overwrite it.

2025-01-16 00:37 UTC, lightmark commented on aptos-move/aptos-vm/src/aptos_vm.rs
> +        );
what's the issue? the aa_gas is free. and we change to a smaller value which is not free?

2025-01-16 01:13 UTC, lightmark commented on aptos-move/aptos-vm/src/aptos_vm.rs
> +        );
oh, yes. Free was the initial idea. I will ensure max_gas is higher

2025-01-16 01:14 UTC, vgao1996 commented on aptos-move/aptos-vm/src/aptos_vm.rs
> +        );
Also consider the non-AA transactions. In that code path there's no point bounding max_gas to max_aa_gas.

2025-01-16 01:15 UTC, lightmark commented on aptos-move/aptos-vm/src/aptos_vm.rs
> +        );
but it's an noop. 
I just read the current code, if max_aa_gas is higher the `adjust_initial_gas` will return an error. What's the problem here?

2025-01-16 01:17 UTC, vgao1996 commented on aptos-move/aptos-vm/src/aptos_vm.rs
> +        );
> if max_aa_gas is higher the adjust_initial_gas will return an error. What's the problem here?

Then you are introducing a global minimum gas aren't you? Not saying we can't do this, but better keep it decoupled from AA.

2025-01-16 01:19 UTC, lightmark commented on aptos-move/aptos-vm/src/aptos_vm.rs
> +        );
what do you mean by decoupled from AA?

2025-01-16 01:20 UTC, vgao1996 commented on aptos-move/aptos-vm/src/aptos_vm.rs
> +        );
Your PR introduces AA as a new code path. I feel like for now should keep the old code path (gas semantics for non-AA transactions) unchanged, so we don't run into expected issues or break people unintentionally.

2025-01-16 01:23 UTC, lightmark commented on aptos-move/aptos-vm/src/aptos_vm.rs
> +        );
I tried to. But your way to create gas meter and gas meter cannot be copied is the issue that I result in the current code.

2025-01-16 01:32 UTC, vgao1996 commented on aptos-move/aptos-vm/src/aptos_vm.rs
> +        );
Well your flow looks like this:
1. Create gas meter
2. Validate transaction (use gas meter, only charge gas when AA is used)
3. Reset the gas meter balance
4. Execution transaction

I think there are two ways you can deal with this:
- If you don't want to charge gas for AA
  - You create a second, throw-away gas meter in step (2)
- If you want to charge gas for AA
  - You set the balance to `min(max_aa_gas, max_gas_amount)` in step (1)
  - In step (3), you bump the balance by `max_gas_amount - min(max_aa_gas, max_gas_amount)`
  - If you want to make it cleaner for the non-AA path, you could set the balance to `max_gas_amount` in step (1) and later not bump it

2025-01-16 01:37 UTC, lightmark commented on aptos-move/aptos-vm/src/aptos_vm.rs
> +        );
if you want to create gas meter based on the AA condition, the gas meter should be created in the execute_user_transaction function. It adds a lot complexities to the refactoring of the current code structure. 

I did as you said at the initial version and pivot to the current code then.

2025-01-16 01:38 UTC, lightmark commented on aptos-move/aptos-vm/src/aptos_vm.rs
> +        );
partially because of ` make_gas_meter: F,`

2025-01-16 01:52 UTC, vgao1996 commented on aptos-move/aptos-vm/src/aptos_vm.rs
> +        );
> partially because of  make_gas_meter: F,

Not exactly sure why this is a problem -- maybe I missed something? 

Wondering why you can't just do this? `make_gas_meter` already allows you to set an initial balance
> You set the balance to min(max_aa_gas, max_gas_amount) in step (1)
> In step (3), you bump the balance by max_gas_amount - min(max_aa_gas, max_gas_amount)

2025-01-16 17:48 UTC, igor-aptos commented on aptos-move/aptos-vm/src/aptos_vm.rs
> +        );
yeah, and also accesses to max_aa_gas don't seem to be gated properly.
 and this might cause the framework upgrade issues as well.

I added a commit that tries to fix it, let's see the test

2025-01-16 20:24 UTC, vgao1996 reviewed
The rest looks good to me

2025-01-16 20:24 UTC, vgao1996 commented on aptos-move/framework/aptos-framework/sources/account/account_abstraction.move
> +        V1 { auth_functions: OrderedMap<FunctionInfo, bool> }
Will this be replaced by function values in the future?

2025-01-16 20:39 UTC, vgao1996 commented on aptos-move/aptos-vm/src/aptos_vm.rs
> +    function_info: FunctionInfo,
Actually @runtian-zhou could you take a look at the usage of dynamic dispatch here?

Is there anything we need to check about the function? Like visibility?

2025-01-16 20:52 UTC, igor-aptos approved these changes
rechecked gating and transaction_validation one more time, with last changes to gas semantics, this looks good to me.

2025-01-16 21:02 UTC, runtian-zhou commented on aptos-move/aptos-vm/src/aptos_vm.rs
> +    function_info: FunctionInfo,
I checked the logics here and this should be fine. Here's my reasoning:

The function info here will be passed into AA authentication function. In that function, we would [check](https://github.com/aptos-labs/aptos-core/blob/7830b6c494c6f0299006a77ff22ef4b542212d4c/aptos-move/framework/aptos-framework/sources/account/account_abstraction.move#L174) if the function info that's been passed in has been registered. In order to register that function in that table, we verified that the function info actually need to meet the type requirements for dispatching [here](https://github.com/aptos-labs/aptos-core/blob/7830b6c494c6f0299006a77ff22ef4b542212d4c/aptos-move/framework/aptos-framework/sources/account/account_abstraction.move#L109). In the native checks, we checked for visibility, type safety, etc [here](https://github.com/aptos-labs/aptos-core/blob/30012b376bf9c7484845ce8dc4768cd920d4a266/aptos-move/framework/src/natives/function_info.rs#L114)

2025-01-16 21:29 UTC, lightmark commented on aptos-move/framework/aptos-framework/sources/account/account_abstraction.move
> +        V1 { auth_functions: OrderedMap<FunctionInfo, bool> }
how?

2025-01-16 23:00 UTC, vgao1996 approved these changes

2025-01-17 01:06 UTC, merged

2025-01-18 12:57 UTC, yeptos commented on aptos-move/framework/aptos-framework/sources/account/account_abstraction.move
> +    public entry fun add_dispatchable_authentication_function(
comment says it's a private entry function but it's not. same for remove_dispatchable_authenticator