[gas] permission
aptos-labs/aptos-core pull request #15232
Opened 2024-11-07 21:40 UTC by lightmark

## Description
add Gas permission

2025-01-08 23:09 UTC, igor-aptos requested changes

2025-01-08 23:09 UTC, igor-aptos commented on aptos-move/framework/aptos-framework/sources/transaction_validation.move
> +                    gas_payer,
wondering if this is truly generic - if the gas payer is fee payer - can it use AA with delegated accounts and have permissioned signer here?

2025-01-08 23:09 UTC, igor-aptos commented on aptos-move/framework/aptos-framework/sources/transaction_validation.move
> +                permissioned_signer::check_permission_consume(
since all transactions are independent - couldn't you check here value without consumption - and then consume below? that would remove the need to compute max_transaction_fee below?

2025-01-13 23:09 UTC, lightmark commented on aptos-move/framework/aptos-framework/sources/transaction_validation.move
> +                    gas_payer,
When signer is passed here. permissioned signer will be passed.

2025-01-15 00:06 UTC, igor-aptos requested changes
since test didn't caught these issues - let's add gas checks to the test.
is 1.2 APT max gas or 1 APT?

how about we keep max_gas to default for first call, and allow only that much in the permission.
and then check that transaction with same max_gas will fail now.
and then transactions later, we half the max_gas, so they all pass from gas perspective.

2025-01-15 00:18 UTC, lightmark commented on aptos-move/framework/aptos-framework/sources/transaction_validation.move
> +                    ((max_transaction_fee + mint_amount) as u256),
sorry, I was so sleepy last night... cuz of jet lag...

2025-01-16 20:32 UTC, runtian-zhou commented on aptos-move/aptos-vm/src/errors.rs
> +                    println!("{:?}", err_msg);
Yea remove this please :D

2025-01-16 20:33 UTC, runtian-zhou commented on aptos-move/framework/aptos-framework/sources/account/permissioned_delegation.move
> +        delegations: Table<DelegationKey, AccountDelegation>
Probably need to rebase here?

2025-01-17 16:47 UTC, igor-aptos approved these changes

2025-01-17 18:09 UTC, runtian-zhou reviewed
Who will pass the gas_payer sender to the prologue? Or in other words, when can the gas_payer be the permissioned signer?

2025-01-17 18:13 UTC, runtian-zhou approved these changes

2025-01-17 18:44 UTC, runtian-zhou commented
Just double checked the code. The fee payer can be a permissioned signer when running an AA in aptos_vm. Looks good to me now.

2025-01-17 18:46 UTC, igor-aptos commented
yes, and if transient signer is used - it's a master signer here, so permission is not used - the max_gas from transaction that user explicitly signed serves that purpose

2025-01-17 22:08 UTC, merged