add `--assume-yes` to all update subcommands
aptos-labs/aptos-core pull request #15536
Opened 2024-12-07 13:36 UTC by mkurnikov

## Description

Fixes https://github.com/aptos-labs/aptos-core/issues/13265

## How Has This Been Tested?

I couldn't find any tests for `aptos update`, so no tests were added. 

## Key Areas to Review

I used separate `assume_yes` field instead of reusing `PromptOptions`, as `--assume-no` does not really make sense in this context. 

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [ ] Move Compiler
- [ ] Other (specify)

## Checklist
- [ ] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I identified and added all stakeholders and component owners affected by this change as reviewers
- [ ] I tested both happy and unhappy path of the functionality
- [ ] I have made corresponding changes to the documentation

2024-12-07 13:40 UTC, mkurnikov commented
@vgao1996

2024-12-11 01:57 UTC, vgao1996 approved these changes

2024-12-11 19:40 UTC, banool requested changes

2024-12-11 19:40 UTC, banool commented on crates/aptos/src/update/aptos.rs
> +    pub assume_yes: bool,
Can you use PromptOptions instead?

2024-12-11 20:17 UTC, mkurnikov commented on crates/aptos/src/update/aptos.rs
> +    pub assume_yes: bool,
Sure, I've changed it.

2024-12-11 20:18 UTC, banool approved these changes
Awesome, ty!

2025-03-05 15:35 UTC, merged