Feature gate permissioned signer
aptos-labs/aptos-core pull request #15622
Opened 2024-12-17 15:19 UTC by runtian-zhou

## Description

## How Has This Been Tested?

## Key Areas to Review

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] Breaking change
- [ ] Performance improvement
- [ ] Refactoring
- [ ] Dependency update
- [ ] Documentation update
- [ ] Tests

## Which Components or Systems Does This Change Impact?
- [ ] Validator Node
- [ ] Full Node (API, Indexer, etc.)
- [ ] Move/Aptos Virtual Machine
- [ ] Aptos Framework
- [ ] Aptos CLI/SDK
- [ ] Developer Infrastructure
- [ ] Move Compiler
- [ ] Other (specify)

## Checklist
- [ ] I have read and followed the [CONTRIBUTING](https://github.com/aptos-labs/aptos-core/blob/main/CONTRIBUTING.md) doc
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I identified and added all stakeholders and component owners affected by this change as reviewers
- [ ] I tested both happy and unhappy path of the functionality
- [ ] I have made corresponding changes to the documentation

2024-12-17 15:19 UTC, runtian-zhou commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/15622?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#15609** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/15609?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#15622** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/15622?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/15622?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#14916** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/14916?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#14605** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/14605?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#14582** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/14582?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#14535** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/14535?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#14567** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/14567?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#14521** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/14521?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#14469** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-core/14469?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2025-01-15 02:45 UTC, rahxephon89 approved these changes

2025-01-15 18:39 UTC, igor-aptos requested changes
relooking - this is not gated properly:

- nobody should be able to make a native call before feature is enabled. so is_permissioned_signer needs to be gated, and also all places that call permission_address - though those seem to be conditional to is_permissioned_signer as far as I can see
-  we should also gate create_permissioned_handle and create_storable_permissioned_handle

2025-01-15 19:39 UTC, igor-aptos approved these changes

2025-01-15 20:08 UTC, merged