[storage] make rocksdb configs separate for ledger_db and state_merkl…
aptos-labs/aptos-core pull request #1661
Opened 2022-06-30 05:50 UTC by msmouse

…e_db

### Description
The state tree needs way more files to be open while the db is large.

### Test Plan
setting max_open_files to -1 (unlimited), on 32 core 128GB test machine I was able to create a 100M accounts DB in 3.5 hours (compared to 4.5 hours while max_open_files = 10k)

2022-06-30 06:00 UTC, sitalkedia reviewed
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/1661)* status: all files reviewed, 1 unresolved discussion (waiting on @grao1991, @lightmark, @msmouse, and @zcchahaha)

___
*[`config/src/config/storage_config.rs` line 32 at r1](https://reviewable.io/reviews/aptos-labs/aptos-core/1661#-N5nBUaY9dIYQked4U5c:-N5nBUaY9dIYQked4U5d:b-jl7o4) ([raw file](https://github.com/aptos-labs/aptos-core/blob/feeca73c421c0861b026bcd77f3b9ff7c85ae097/config/src/config/storage_config.rs#L32)):*
> ```XML
>             ledger_db_config: RocksdbConfig {
>                 // Allow db to close old sst files, saving memory.
>                 max_open_files: 1000,
> ```

Should we keep the default same as before? Will reducing it cause any regression in production?


<!-- Sent from Reviewable.io -->

2022-06-30 18:50 UTC, msmouse reviewed
> *[Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/1661)* status: all files reviewed, 1 unresolved discussion (waiting on @grao1991, @lightmark, @sitalkedia, and @zcchahaha)

___
*[`config/src/config/storage_config.rs` line 32 at r1](https://reviewable.io/reviews/aptos-labs/aptos-core/1661#-N5nBUaY9dIYQked4U5c:-N5pw53rDCnvU1_iC2sT:b-1pifci) ([raw file](https://github.com/aptos-labs/aptos-core/blob/feeca73c421c0861b026bcd77f3b9ff7c85ae097/config/src/config/storage_config.rs#L32)):*
<details><summary><i>Previously, sitalkedia (Sital Kedia) wrote…</i></summary><blockquote>

Should we keep the default same as before? Will reducing it cause any regression in production?
</blockquote></details>

The old value is for a single DB holding the content of both the new DBs.  

The ledger db in theory needs less files open.

But I realized the state values are in the ledger db as well.. gonna update both the default values to half the original for now. (Because too many files open can OOM our typical set up)


<!-- Sent from Reviewable.io -->

2022-06-30 19:08 UTC, lightmark requested changes
> *[Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/1661)* status: all files reviewed, 2 unresolved discussions (waiting on @grao1991, @msmouse, @sitalkedia, and @zcchahaha)

___
*[`execution/executor-benchmark/src/db_generator.rs` line 41 at r1](https://reviewable.io/reviews/aptos-labs/aptos-core/1661#-N5q-thr50gP-9OJFxgB:-N5q-thr50gP-9OJFxgC:b-fm2243) ([raw file](https://github.com/aptos-labs/aptos-core/blob/feeca73c421c0861b026bcd77f3b9ff7c85ae097/execution/executor-benchmark/src/db_generator.rs#L41)):*
> ```XML
>     // Create executor.
>     let mut rocksdb_configs = RocksdbConfigs::default();
>     rocksdb_configs.state_merkle_db_config.max_open_files = -1;
> ```

What's this for?


<!-- Sent from Reviewable.io -->

2022-06-30 19:09 UTC, lightmark commented
I don't mean to request change, still getting used to the new tool...

2022-06-30 19:15 UTC, msmouse reviewed
> *[Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/1661)* status: all files reviewed, 2 unresolved discussions (waiting on @grao1991, @lightmark, @sitalkedia, and @zcchahaha)

___
*[`execution/executor-benchmark/src/db_generator.rs` line 41 at r1](https://reviewable.io/reviews/aptos-labs/aptos-core/1661#-N5q-thr50gP-9OJFxgB:-N5q1JO_5HBDoEf2pF1q:b-wvptss) ([raw file](https://github.com/aptos-labs/aptos-core/blob/feeca73c421c0861b026bcd77f3b9ff7c85ae097/execution/executor-benchmark/src/db_generator.rs#L41)):*
<details><summary><i>Previously, lightmark (Aaron) wrote…</i></summary><blockquote>

What's this for?
</blockquote></details>

When creating 100M accounts, it starts closing and opening files frequently (my guess), making it unlimited lowered the time to create 100M accounts from more than 4.5 hours to 3.5 hours.


<!-- Sent from Reviewable.io -->

2022-06-30 19:50 UTC, grao1991 approved these changes

2022-07-01 19:07 UTC, lightmark approved these changes
> Reviewed 11 of 13 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/1661)* status: all files reviewed, 2 unresolved discussions (waiting on @lightmark, @sitalkedia, and @zcchahaha)



<!-- Sent from Reviewable.io -->

2022-07-01 19:07 UTC, merged