[Aptos Framework] Add built-in framework stake delegations support
aptos-labs/aptos-core pull request #2169
Opened 2022-07-23 17:01 UTC by movekevin

### Description

### Test Plan

2022-07-29 03:16 UTC, davidiw requested changes
can we put this into move-examples with some tests?

2022-08-15 08:58 UTC, bharath-123 commented
Hi @movekevin I want to write a move module which can delegate to a validator. I believe there is no support to delegate to a validator yet if i m right? If so, is there an estimate on when it would be available?

2022-08-18 19:04 UTC, gregnazario commented
Is this still valid @movekevin ?

2022-08-19 02:46 UTC, movekevin commented
> Is this still valid @movekevin ?

Nope. I've had time to update this after we changed the stake module's lockup model

2022-08-25 06:23 UTC, closed without merging