[cli][consensus] Add analyze-validator-performance to node cli
aptos-labs/aptos-core pull request #2364
Opened 2022-07-29 23:59 UTC by ikabiljo

Adding utilities to analyze validator performance, based on accessing live on-chain data 

Fastest to run a full node locally, and connecting cli to it.

Currently fetching from all transactions. We can fetch create API for just metadata transactions and/or fetch from BigQuery, if this is too slow for people. When we run loadtest, and BlockMetadata transactions are not the majority, it does slow down. 

Test Plan:
cargo run -p aptos -- node analyze-validator-performance --analyze-mode=all

2022-07-30 00:16 UTC, sitalkedia commented
@ikabiljo  - Possible to split this into two PRs for easier review? I see its addressing two different functionalities one for each commit?

2022-07-30 02:36 UTC, ikabiljo commented
sorry, github issues with stacked PRs.

Corrected it now, it's now showing only one change. 

Other one is a separate PR already.

2022-07-31 14:57 UTC, sitalkedia commented on crates/aptos/src/node/analyze_validators.rs
> +            validator_stats,
nit: let's create a constructor of `EpochStats` to make it less verbose.

2022-07-31 14:57 UTC, sitalkedia commented on crates/aptos/src/node/analyze_validators.rs
> +                    start_seq_num = raw_event.event.sequence_number();
It's not really start seq number as you are updating it everytime.

2022-07-31 14:57 UTC, sitalkedia commented on crates/aptos/src/node/analyze_validators.rs
> +            let is_nil = event.proposer() == AccountAddress::ZERO;
Just curious, when will this happen?

2022-07-31 14:57 UTC, sitalkedia commented on crates/aptos/src/node/analyze_validators.rs
> +impl AnalyzeValidators {
nit: Would be good to move this struct to a separate module.

2022-07-31 14:57 UTC, sitalkedia commented on types/src/account_config/events/new_block.rs
> +    // #[cfg(any(test, feature = "fuzzing"))]
nit: lets remove this

2022-07-31 14:57 UTC, sitalkedia commented on crates/aptos/src/node/fetch_metadata.rs
> +            for validator in active_validators {
nit: many nested if-else making this code a bit unreadable. Possible to simplify or may be create a helper function to extract the address?

2022-07-31 14:57 UTC, sitalkedia commented on crates/aptos/src/node/fetch_metadata.rs
> +                while start_version + 5 * batch < search_end {
Can you explain what is magic number 5 for and possibly add a comment here?

2022-07-31 14:57 UTC, sitalkedia commented on testsuite/smoke-test/src/leader_election.rs
> +    // println!(
nit: please remove

2022-07-31 14:57 UTC, sitalkedia commented on testsuite/smoke-test/src/leader_election.rs
> +    // validator_clients[1].set_failpoint("consensus::process_proposal_msg".to_string(), "100%return".to_string()).await.unwrap();
please remove

2022-07-31 14:57 UTC, sitalkedia commented on testsuite/smoke-test/src/leader_election.rs
> +fn get_validator_addresses(data: &MoveResource, field_name: &str) -> Option<Vec<AccountAddress>> {
Let's reuse this code in `fetch_metadata.rs` ?

2022-07-31 14:57 UTC, sitalkedia commented on testsuite/smoke-test/src/leader_election.rs
> +    let client = RestClient::new(Url::parse("https://sherryx.aptosdev.com").unwrap()); //"http://127.0.0.1:8080").unwrap());
I am wondering how stable this test will be if it depends on sherry-net ?

2022-07-31 15:50 UTC, ikabiljo commented
Sorry, smoke_test was accidentally added,  that's how I used it before extracting and putting into CLI, I'll remove it.

2022-08-01 17:18 UTC, ikabiljo commented on crates/aptos/src/node/analyze_validators.rs
> +    /// Number of successful proposals
It is used for both - this just represents stats over some period of time, what is it filled with affects what it means

2022-08-01 17:44 UTC, ikabiljo commented on crates/aptos/src/node/analyze_validators.rs
> +pub enum NodeState {
nobody is really only proposing, but people have meaningfully small number of votes - but that is hard to show with enum

maybe:
- RELIABLE  (proposal failure < 10%)
- ALIVE_UNRELIABLE (has successful proposals, but proposal failure > 10%)
- ONLY_VOTING (no successful proposals, but voting)
- DOWN (not participating in consensus)
- NOT_IN_VALIDATOR_SET

2022-08-09 22:46 UTC, ikabiljo commented
other changes on main allowed me to simplify fetching logic (using fetching events). So this should also be faster now.

@sitalkedia , @zekun000  this is ready for review

2022-08-12 04:12 UTC, sitalkedia requested changes
> *[Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/2364)* status: 0 of 13 files reviewed, 18 unresolved discussions (waiting on @banool, @bchocho, @gregnazario, @ikabiljo, @sitalkedia, and @zekun000)

___
*[`crates/aptos/src/node/mod.rs` line 734 at r2](https://reviewable.io/reviews/aptos-labs/aptos-core/2364#-N9F8v9n72dVyeS9JVM3:-N9F8v9n72dVyeS9JVM4:b-g01tyx) ([raw file](https://github.com/aptos-labs/aptos-core/blob/d8ffdf7f80a829593558dc4b2556a8e6c7137c68/crates/aptos/src/node/mod.rs#L734)):*
> ```XML
> #[derive(PartialEq, clap::ArgEnum, Clone)]
> pub enum AnalyzeMode {
>     All,
> ```

nit: It would be good to add comment explaining what each mode means. As well as adding the same in 
___
*[`crates/aptos/src/node/mod.rs` line 779 at r2](https://reviewable.io/reviews/aptos-labs/aptos-core/2364#-N9F9y8R8LR7Zc3jy1if:-N9F9y8R8LR7Zc3jy1ig:bbnjkxx) ([raw file](https://github.com/aptos-labs/aptos-core/blob/d8ffdf7f80a829593558dc4b2556a8e6c7137c68/crates/aptos/src/node/mod.rs#L779)):*
> ```XML
>         }
>         let all_validators: Vec<_> = total_stats.validator_stats.keys().cloned().collect();
>         if self.analyze_mode == AnalyzeMode::ValidatorHealthOverTime
> ```

nit: A `match` statement would be cleaner to replace this `if statement` and statement below.
___
*[`testsuite/smoke-test/src/leader_election.rs` line 4 at r2](https://reviewable.io/reviews/aptos-labs/aptos-core/2364#-N9FFAfcAE-ATLP91KoU:-N9FFAfcAE-ATLP91KoV:bswedih) ([raw file](https://github.com/aptos-labs/aptos-core/blob/d8ffdf7f80a829593558dc4b2556a8e6c7137c68/testsuite/smoke-test/src/leader_election.rs#L4)):*
> ```XML
> // SPDX-License-Identifier: Apache-2.0
> 
> use consensus::analyze_validators::{AnalyzeLeaderSelection, EpochStats};
> ```

You missed to remove this file? 
___
*[`crates/aptos/src/node/analyze_validators.rs` line 162 at r1](https://reviewable.io/reviews/aptos-labs/aptos-core/2364#-N8BOZXNKfkAuua_KF-H-r1-162:-N9FDyry1xbPl-XleHHs:b-b34ylo) ([raw file](https://github.com/aptos-labs/aptos-core/blob/d56dcc9a191fa7e65a5a7120ca813e6e3f88fc00/crates/aptos/src/node/analyze_validators.rs#L162)):*
<details><summary><i>Previously, sitalkedia (Sital Kedia) wrote…</i></summary><blockquote>

nit: Would be good to move this struct to a separate module.
</blockquote></details>

Can you add this ^^ ? 


<!-- Sent from Reviewable.io -->

2022-08-12 04:13 UTC, sitalkedia approved these changes
> Reviewed 1 of 7 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aptos-labs/aptos-core/2364)* status: all files reviewed, 18 unresolved discussions (waiting on @banool, @bchocho, @gregnazario, @ikabiljo, @sitalkedia, and @zekun000)



<!-- Sent from Reviewable.io -->

2022-08-12 15:48 UTC, ikabiljo commented
*[`crates/aptos/src/node/mod.rs` line 779 at r2](https://reviewable.io/reviews/aptos-labs/aptos-core/2364#-N9F9y8R8LR7Zc3jy1if:-N9F9y8R8LR7Zc3jy1ig:bbnjkxx) ([raw file](https://github.com/aptos-labs/aptos-core/blob/d8ffdf7f80a829593558dc4b2556a8e6c7137c68/crates/aptos/src/node/mod.rs#L779)):*
> ```XML
>         }
>         let all_validators: Vec<_> = total_stats.validator_stats.keys().cloned().collect();
>         if self.analyze_mode == AnalyzeMode::ValidatorHealthOverTime
> ```

> nit: A `match` statement would be cleaner to replace this `if statement` and statement below.

with match statement, I would need to duplicate the calls instead (because ALL calls both summaries - so seems like a similar complexity

2022-08-12 19:40 UTC, merged