[testing][move][swarm] Add flag to execute block prologue natively (for tests)
aptos-labs/aptos-core pull request #2999
Opened 2022-08-16 04:05 UTC by igor-aptos

### Description

80% of CPU in local swarm (run in debug mode) is consumed by loading modules.

On empty blocks, only block prologue is executed, and it is simple, except for validator statistics for rewards, and for epoch change. 

So creating a flag that enables block prologue to be executed in rust code only, (used for testing, as it is incompatible difference - as validator statistics are not updated), except for the epoch change.

On my machine, reduces empty block execution from 160ms to 2ms.
This allows me to have 50-100 blocks per second, instead of 5 - enabling much better and faster consensus tests.
On top of that it reduces CPU usage for all smoke tests, making them significantly faster and less flaky.

Because this is so big of a difference, that it should be used always, except when rewards are being tested, but makes logic different from prod - I made it an explicitly clear what is being used with:
SwarmBuilder::new_local_optimized_without_rewards
SwarmBuilder::new_local_with_rewards

It would probably be useful to have lazy loading in move, but only on access - as block.move links all the code, but uses most of it only on epoch change.

### Test Plan
all smoke tests

I'll add separately some rewards e2e swarm tests, and those will not be using above flag.

2022-08-16 04:37 UTC, zekun000 requested changes
hmm, this seems very hacky, I'd rather us optimize the loader, I think just use release mode reduces the time to a few ms. maybe just add --release here and try?

2022-08-16 16:44 UTC, igor-aptos commented
@zekun000 :
using --release, empty block drops from 150-200ms to 10-15ms (compared to 2ms), that's good enough.

But release experience for tests is quite bad, not sure whether we should prefer that. It took 7mins to compile the node after rebasing with a day worth of changes, and single line change took 2 minutes to compile the node. For tests - not sure that is worth it.

Third alternative is, most of the time is spent in verifying - I am not sure if we can disable verifying or not re-verify if no module was changed in the meantime. I don't see a good way to do that though, as the VM API doesn't seem to provide options for that.

Let me know which option do you think we should go with?

2022-08-16 16:57 UTC, zekun000 commented
agree the compile time is a pain, i think we can investigate in reuse the vm across blocks as well as adding flags to disable some heavy vm operations (in move repo), let’s discuss in #move channel

2022-09-08 05:40 UTC, davidiw commented
closing an oldr pr.

2022-09-08 05:40 UTC, closed without merging