Update first-move-module.md
aptos-labs/aptos-core pull request #3184
Opened 2022-08-19 16:06 UTC by Fei94043

### Description

### Test Plan

2022-08-23 05:49 UTC, davidiw reviewed
this is great, as you're probably aware, we're rewriting the tutorials, so I'll keep this in mind. One nit, you include your user paths, whereas using relative paths would be better

2022-08-23 06:08 UTC, rajkaramchedu requested changes

2022-08-23 06:08 UTC, rajkaramchedu commented on developer-docs-site/docs/tutorials/first-move-module.md
>  You can find the rust project [here](https://github.com/aptos-labs/aptos-core/tree/main/developer-docs-site/static/examples/rust)
rust → Rust

2022-08-23 06:08 UTC, rajkaramchedu commented on developer-docs-site/docs/tutorials/first-move-module.md
>  You can find the rust project [here](https://github.com/aptos-labs/aptos-core/tree/main/developer-docs-site/static/examples/rust)
Put a period at the end of either "here" as `[here.]` or after the closing bracket of the link.

2022-08-23 06:08 UTC, rajkaramchedu commented on developer-docs-site/docs/tutorials/first-move-module.md
> +
I suggest we remove the above passage. We should rely on the intelligence of the reader to figure this out themselves. Or else we will have to tell them a whole lot more low-level things to be consistent in our docs.

2022-08-23 06:08 UTC, rajkaramchedu commented on developer-docs-site/docs/tutorials/first-move-module.md
> + python git:(c6841bd6b0) python3 hello_blockchain.py Message.mv
What is this `python git:(c6841bd6b0)`? Maybe this is part of the command line prompt on your local terminal? Remove this please. The correct command is `python3 hello_blockchain.py Message.mv`

2022-08-23 06:08 UTC, rajkaramchedu commented on developer-docs-site/docs/tutorials/first-move-module.md
> +➜  hello_blockchain git:(c6841bd6b0) aptos move compile --package-dir . --named-addresses HelloBlockchain=0x10bf3a5f10a4dcd6b387221559ca4cf6ead4850ae3499816494fd94845938d7b
Remove `hello_blockchain git:(c6841bd6b0)`

2022-08-23 06:08 UTC, rajkaramchedu commented on developer-docs-site/docs/tutorials/first-move-module.md
> +➜  bytecode_modules git:(c6841bd6b0) cp message.mv /Users/feizheng/aptos-core/developer-docs-site/static/examples/python/
Remove `bytecode_modules git:(c6841bd6b0)`

2022-08-30 05:23 UTC, davidiw commented
Please review the updated doc. I think much of the feedback has been integrated. Agreed with @rajkaramchedu  we cannot ... simplify it too much.

2022-08-30 05:23 UTC, closed without merging