Update in-korean.md
aptos-labs/aptos-core pull request #3520
Opened 2022-08-26 12:08 UTC by lukeyang

Some editorial changes proposal and fixed broken link for PDF files.

### Description
Editorial changes for Korean sentences and fixing broken link for PDF whitepaper files.

### Test Plan

2022-08-26 14:09 UTC, davidiw reviewed
The links work for me on the original but not this one. What happens when you click the links? @bchocho / @junkil-park can you validate the Korean contributions?

2022-08-26 16:54 UTC, bchocho commented
@davidiw really? It's the opposite for me. Only the updated links work.
* Original: https://github.com/aptos-labs/aptos-core/blob/main/papers/whitepaper-korean.pdf (I get a 404)
* Updated: https://github.com/aptos-labs/aptos-core/blob/main/developer-docs-site/static/papers/whitepaper-korean.pdf

I'll take a look at the Korean changes :)

2022-08-26 16:57 UTC, davidiw commented
oh jeez... these links are for the website not for github ... this is one of the disadvantages of docusaurus @rajkaramchedu -- something to look into.

2022-08-26 17:00 UTC, bchocho requested changes
수정 감사합니다! 코멘트 달았습니다.

2022-08-27 04:43 UTC, rajkaramchedu requested changes

2022-08-27 04:43 UTC, rajkaramchedu commented on developer-docs-site/docs/aptos-white-paper/in-korean.md
> +- **초록**: Aptos 백서의 한국어 버전 전체 PDF를 보려면 [여기를 클릭하십시오](/developer-docs-site/static/papers/whitepaper-korean.pdf).
Why is this linked to HTML page when the admonition clearly says these are links to the PDF docs? This correction is incorrect. Docusaurus links should be done in a specific way, just see how the original is "/papers/...".

2022-08-27 04:43 UTC, rajkaramchedu commented on developer-docs-site/docs/aptos-white-paper/in-korean.md
> +- **English**: Click [here for the full PDF of the Aptos White Paper](/developer-docs-site/static/papers/Aptos-Whitepaper.pdf).
Incorrect link. Original link is correct and works.

2022-08-27 04:47 UTC, rajkaramchedu commented
@lukeyang you said, "fixed broken link for PDF files." Which browser are you using? What exactly happens when you click on the PDF link? These links are correct and they were tested working before publishing. Please be specific in how they are broken for you so I can look into it. kamsamida :- )

2022-08-27 05:26 UTC, lukeyang commented
@rajkaramchedu 

After the release of Korean white paper, pdf release was widely spread in the Korean community. But the spread link was https://github.com/aptos-labs/aptos-core/blob/main/developer-docs-site/static/papers/whitepaper-korean.pdf, not https://aptos.dev/assets/files/whitepaper-korean-67e84101467803b96c4f481a1161ec45.pdf

As a native Korean, I wanted to correct some Korean sentences. During reviewing the documents, I thought that the pdf link was broken, because of my misunderstanding of docusaurus.

What I thought the link is broken in this document release : https://github.com/aptos-labs/aptos-core/blob/main/papers/whitepaper-korean.pdf 
What I thought the link should be fixed : https://github.com/aptos-labs/aptos-core/blob/main/developer-docs-site/static/papers/whitepaper-korean.pdf

But I saw the comments from @bchocho the the link is correct in https://aptos.dev link. My correct suggestion for the link was wrong. Sorry for confusion. Only some minor Korean sentences correction make sense.

FYI, I use Chome in Mac m1 machine.

2022-08-27 05:34 UTC, rajkaramchedu commented
Perfect, thanks, @lukeyang for the contextual explanation. I see that now. Okay, so if you now push the changes only to the Korean sentences and retain the original PDF links, I will approve this and we can land this asap. Thanks again!

2022-08-27 15:06 UTC, bchocho requested changes
Can you please also change the last instance of 어플리케이션 on line 36?

2022-08-27 16:08 UTC, bchocho approved these changes
Thank you!

2022-08-28 05:17 UTC, bchocho commented
@rajkaramchedu when you get the chance can you accept as well? :)

2022-08-28 13:07 UTC, rajkaramchedu approved these changes

2022-08-29 02:49 UTC, merged