[observability] remove obsolete remote logger functionality from terr…
aptos-labs/aptos-core pull request #4022
Opened 2022-09-09 09:04 UTC by geekflyer

…aform/helm

### Description

This removes the obsolete remote logger functionality from our terraform + helm config.
This is superseded by using the vector DaemonSet helm chart which collects logs from stdout.

### Test Plan

2022-09-10 00:10 UTC, rustielin requested changes
I'd like to at least keep an option to install the logger via Terraform, even if it defaults to false. Other than that, just a few nits

2022-09-10 00:10 UTC, rustielin commented on terraform/aptos-node/aws/variables.tf
> -variable "enable_logger" {
can you replace this with an option to install the new vector daemonset? even if we leave it off for our uses to helm install via some other process, it's still useful to have an option in terraform for 1-click deployment with logging and monitoring

2022-09-10 00:10 UTC, rustielin commented on terraform/fullnode/vultr/.terraform.lock.hcl
> +    "h1:9yMFsXyHAo+mUuMKczNSw44HcZaf1JkMqgOUgJF1dXs=",
we can probably leave out these terraform lockfiles, since they're meant to be invoked as modules

2022-09-10 00:10 UTC, rustielin commented on terraform/helm/aptos-node/values.yaml
> +  rust_log_remote: off
this disables the remote logging functionality of the `aptos-logger` crate right? 
if so, might be useful to include some docs on how to configure that (setting the remote log level and the address)

2022-09-21 04:06 UTC, davidiw commented
closing out as stale.

2022-09-21 04:06 UTC, closed without merging