[aptos-vm] disable modules during prologue
aptos-labs/aptos-core pull request #4083
Opened 2022-09-11 00:44 UTC by davidiw

since we want to delete this as much as possible, we need to prevent them from getting into mempool and hitting a committed but discarded state. To that end, we need protect further upstream. We already added an abort call in the VM for testnet to protect it, but that's a hack considering the code situation. Moving this in here simplifies testnet, makes sure weird behavior cannot happen on devnet (e.g., committed but aborted ModuleBundle), and makes it so we don't have to think about it for mainnet.

I would have deleted the ModuleBundle code, but it looks like @wrwg is using it to validate module upgrades work as expected for now.

### Description

### Test Plan

2022-09-11 01:43 UTC, movekevin approved these changes
We only ever had unit tests for the old module bundle flow? :(

2022-09-11 01:46 UTC, davidiw commented
No, there are move smoke tests. @wrwg is keeping them around until we add more for the new flow to ensure compatibility. That's why we have this weird hack on gating module publishing.

2022-09-11 20:32 UTC, wrwg commented
> No, there are move smoke tests. @wrwg is keeping them around until we add more for the new flow to ensure compatibility. That's why we have this weird hack on gating module publishing.

Just to be clear, there are/have been since ever/Diem a bunch of bundle-based tests for compatibility and other areas. Removing those tests would require us to re-engineer the test coverage in other ways. This is too risky right now.

2022-09-11 20:33 UTC, wrwg commented
> > No, there are move smoke tests. @wrwg is keeping them around until we add more for the new flow to ensure compatibility. That's why we have this weird hack on gating module publishing.
> 
> Just to be clear, there are/have been since ever/Diem a bunch of bundle-based tests for compatibility and other areas. Removing those tests would require us to re-engineer the test coverage in other ways. This is too risky right now.

And we doe have a dozen tests or so for the new publishing flow.

2022-09-11 20:33 UTC, wrwg approved these changes

2022-09-11 20:35 UTC, wrwg requested changes
Actually taking back approval: I'm not seeing how you prevent that module bundles are used outside of tests. Can you elaborate?

If module bundles are still possible in production, all the hardening work in `code.move` is for nothing. ;-)

2022-09-12 01:41 UTC, davidiw commented
>Actually taking back approval: I'm not seeing how you prevent that module bundles are used outside of tests. Can you elaborate?

> If module bundles are still possible in production, all the hardening work in code.move is for nothing. ;-)

The current implementation only rejects a module payload during execution. Execution only happens AFTER the transaction has been accepted into consensus. The current code WILL allow module bundle payloads to be committed to the blockchain. This prevents them from making even making it into mempool and hence prevents them from ever being committed to the chain.

This was already demonstrated in testnet when individuals were very confused why their module bundle payloads were not rejected by the publishing tool and only found out by checking the blockchain to see committed but aborted.

2022-09-12 01:46 UTC, wrwg commented
> > Actually taking back approval: I'm not seeing how you prevent that module bundles are used outside of tests. Can you elaborate?
> 
> > If module bundles are still possible in production, all the hardening work in code.move is for nothing. ;-)
> 
> The current implementation only rejects a module payload during execution. Execution only happens AFTER the transaction has been accepted into consensus. The current code WILL allow module bundle payloads to be committed to the blockchain. This prevents them from making even making it into mempool and hence prevents them from ever being committed to the chain.
> 
> This was already demonstrated in testnet when individuals were very confused why their module bundle payloads were not rejected by the publishing tool and only found out by checking the blockchain to see committed but aborted.

Preventing them to getting into Mempool happened in a different PR? I'm just asking because in this PR I only see removal of a check, and the PR description is also not very clear to me.

2022-09-12 02:11 UTC, davidiw commented
> Preventing them to getting into Mempool happened in a different PR? I'm just asking because in this PR I only see removal of a check, and the PR description is also not very clear to me.

That's not right. Otherwise the tests that I have removed would have failed. We wouldn't have had the issue in devnet where users were able to successfully submit module bundle txns.

With regards to those tests, I could potentially toggle the logic to make `MODULE_BUNDLE_DISALLOWED` this false or removed them. I ultimately just removed them as tech debt, since we're not coming back to module bundle txns.

2022-09-12 02:24 UTC, wrwg commented
> > Preventing them to getting into Mempool happened in a different PR? I'm just asking because in this PR I only see removal of a check, and the PR description is also not very clear to me.
> 
> That's not right. Otherwise the tests that I have removed would have failed. We wouldn't have had the issue in devnet where users were able to successfully submit module bundle txns.
> 
> With regards to those tests, I could potentially toggle the logic to make `MODULE_BUNDLE_DISALLOWED` this false or removed them. I ultimately just removed them as tech debt, since we're not coming back to module bundle txns.

Sorry, not groking what you mean.

I see a PR with two files, one removes a check which disallowed module bundles, the other some tests. What I'm wondering if that check is not longer needed on txn level in the VM, where else is it happening? This is definitely not in this PR. So did it happen before?

I just want to be sure that you did not accidentally forget to add some files to this PR and module bundles stay to be impossible to submit on any network.

2022-09-12 02:45 UTC, davidiw commented
![image](https://user-images.githubusercontent.com/73818/189564308-0dfd194b-ee6a-4f26-8e78-e729d482cf78.png)

I'm adding a check in the prologue to reject these bundles by default and only allow them to pass if this toggle is set. This toggle is set only in tests.

https://github.com/aptos-labs/aptos-core/blob/5c4696f3c12fa28e18908367779c807c89bc699f/aptos-move/aptos-vm/src/aptos_vm.rs#L78

![image](https://user-images.githubusercontent.com/73818/189564487-d83d893c-5619-4299-a470-8d5e3884bc6a.png)

Mempool uses vm-validator to validate transactions: https://github.com/aptos-labs/aptos-core/blob/73205a444df516e748bc574c672d2ff7d69cb0d6/vm-validator/src/vm_validator.rs#L76

That calls into aptos vm: https://github.com/aptos-labs/aptos-core/blob/5c4696f3c12fa28e18908367779c807c89bc699f/aptos-move/aptos-vm/src/aptos_vm.rs#L925

That calls into adapter, which exits after calling prologue: https://github.com/aptos-labs/aptos-core/blob/5c4696f3c12fa28e18908367779c807c89bc699f/aptos-move/aptos-vm/src/adapter_common.rs#L127

Prologue currently has no such check: https://github.com/aptos-labs/aptos-core/blob/5c4696f3c12fa28e18908367779c807c89bc699f/aptos-move/aptos-vm/src/aptos_vm.rs#L863

Which this PR adds.

2022-09-12 02:46 UTC, davidiw commented
Its a fairly minor change and I can see why we missed it in the first PR :sob:.

2022-09-12 02:50 UTC, wrwg approved these changes

2022-09-12 02:59 UTC, wrwg commented
> ![image](https://user-images.githubusercontent.com/73818/189564308-0dfd194b-ee6a-4f26-8e78-e729d482cf78.png)
> 
> I'm adding a check in the prologue to reject these bundles by default and only allow them to pass if this toggle is set. This toggle is set only in tests.
> 
> https://github.com/aptos-labs/aptos-core/blob/5c4696f3c12fa28e18908367779c807c89bc699f/aptos-move/aptos-vm/src/aptos_vm.rs#L78
> 
> ![image](https://user-images.githubusercontent.com/73818/189564487-d83d893c-5619-4299-a470-8d5e3884bc6a.png)
> 
> Mempool uses vm-validator to validate transactions:
> 
> https://github.com/aptos-labs/aptos-core/blob/73205a444df516e748bc574c672d2ff7d69cb0d6/vm-validator/src/vm_validator.rs#L76
> 
> That calls into aptos vm:
> 
> https://github.com/aptos-labs/aptos-core/blob/5c4696f3c12fa28e18908367779c807c89bc699f/aptos-move/aptos-vm/src/aptos_vm.rs#L925
> 
> That calls into adapter, which exits after calling prologue:
> 
> https://github.com/aptos-labs/aptos-core/blob/5c4696f3c12fa28e18908367779c807c89bc699f/aptos-move/aptos-vm/src/adapter_common.rs#L127
> 
> Prologue currently has no such check:
> 
> https://github.com/aptos-labs/aptos-core/blob/5c4696f3c12fa28e18908367779c807c89bc699f/aptos-move/aptos-vm/src/aptos_vm.rs#L863
> 
> Which this PR adds.

Thanks for the explanation -- I simply parsed the PR wrong in that it was adding code instead of removing .... All good!

2022-09-13 03:31 UTC, merged