[Token] create a general token event store for new token events
aptos-labs/aptos-core pull request #4401
Opened 2022-09-21 00:04 UTC by areshand

### Description
1. create a new token event store for all future new token events
2. reorganize the code based on entry, public and private/friend to different sections for easy navigating
3. use transfer event as an example for this general token store. 

### Test Plan
add unit test

2022-09-21 00:05 UTC, areshand commented on aptos-move/framework/aptos-token/sources/token.move
> +    public entry fun mutate_token_properties(
this is simply a copy and re-organize

2022-09-21 00:05 UTC, areshand commented on aptos-move/framework/aptos-token/sources/token.move
> +    public entry fun create_token_script(
this is simply a copy and re-organize

2022-09-21 00:05 UTC, areshand commented on aptos-move/framework/aptos-token/sources/token.move
> +    public entry fun burn(
this is simply a copy and re-organize

2022-09-21 00:06 UTC, areshand commented on aptos-move/framework/aptos-token/sources/token.move
> +    fun update_token_property_internal(
this is simply a copy and re-organize as well

2022-09-25 13:31 UTC, movekevin approved these changes

2022-09-27 00:15 UTC, bowenyang007 commented
Can we see this in action? If we can get a transaction in testnet i can try to parse it out. 

One concern i have is that property map will be bcs encoded which means that the node API will be effectively unusable for those events. It'll be gibberish and people won't know what to do with them. cc @gregnazario

2022-09-27 16:53 UTC, bowenyang007 requested changes
Wanted to make sure that we don't land this before having proper testing...unit tests aren't good enough to test if a standard's usability. Let's do better here especially given this is designed to be the standard for all events moving forward.

2022-09-28 04:33 UTC, davidiw requested changes
Thanks for pushing on this... after discussion today, the indexer folks do not feel the need for this as a mainnet requirement. the reality is that due to the lack of ecosystem projects using many of these interfaces, we should spend more time to evaluate the right direction here.

I'd also like for us to consider how we might make an event stream that doesn't require serialization

2022-09-29 02:45 UTC, closed without merging