Revise Life of a Transaction diagram in LucidChart for light and dark…
aptos-labs/aptos-core pull request #4693
Opened 2022-09-30 23:03 UTC by clay-aptos

… mode

### Description

### Test Plan

2022-09-30 23:26 UTC, clay-aptos commented
I may have fubared the images attempting to address merge conflicts arising from new revisions to the images (making one final box transparent). So here they are for posterity:

![lifecycle-transaction-light](https://user-images.githubusercontent.com/114445310/193368814-47e6d7e0-0bfb-4155-9fc7-529e88336f63.svg)
![lifecycle-transaction-dark](https://user-images.githubusercontent.com/114445310/193368817-6ef878f7-9829-43a8-9948-f3dade69ee17.svg)

2022-09-30 23:28 UTC, rajkaramchedu commented
Docs build failed. @clay-aptos just in case you didn't see. Happy Friday :- )

2022-09-30 23:34 UTC, rajkaramchedu commented
Here is the build failure log. It is complaining about broken link. https://app.netlify.com/sites/aptos-developer-docs/deploys/63377a13b805b000095c65e5

2022-09-30 23:35 UTC, rajkaramchedu requested changes

2022-09-30 23:35 UTC, rajkaramchedu commented on developer-docs-site/docs/guides/basics-life-of-txn.md
>  <small className="figure">Figure 1.0 Lifecycle of a transaction</small>
I've been removing figure numbers since they are manual and it's hard to keep track of them manually. Suggest remove it from here.

2022-09-30 23:57 UTC, rajkaramchedu commented
Note: I will pull this branch and fix it tomorrow (Saturday).

2022-10-03 11:55 UTC, rajkaramchedu approved these changes

2022-10-03 15:57 UTC, clay-aptos commented
Thanks for all of your work on this, @rajkaramchedu ! Unless we need to replace JSON-RPC with REST, I believe this work is done. Will merge in now. Thanks again!

2022-10-03 16:18 UTC, rajkaramchedu commented
> Thanks for all of your work on this, @rajkaramchedu ! Unless we need to replace JSON-RPC with REST, I believe this work is done. Will merge in now. Thanks again!

Land ho, already! :- )

2022-10-03 16:26 UTC, rajkaramchedu commented
> > > Thanks for all of your work on this, @rajkaramchedu ! Unless we need to replace JSON-RPC with REST, I believe this work is done. Will merge in now. Thanks again!
> > 
> > 
> > Land ho, already! :- )
> 
> Actually, it looks like my PRs need two approvers.

All PRs need two approvers. @gregnazario is usually our good samaritan in this case.

2022-10-04 06:11 UTC, gregnazario approved these changes
Let's follow up and change JSON-RPC to REST

2022-10-04 06:11 UTC, merged