markuze/haproxy fullnode docker
aptos-labs/aptos-core pull request #4738
Opened 2022-10-03 22:42 UTC by Markuze

- [forge] fix grafana namespace (#4602)
- [HApropxy] new haproxy config and resources
- [Docker] Adding HAProxy to docker compose
- [tokio-console] Configuring tokio-console default port
- [aptos-cli] Bump to version 0.3.6
- [storage] larger default state prune window
- refactor: add "strict" to SDK tsconfig
- [helm][aptos-node] override NodeConfig with deep merge (#4546)
- add indexer to cli (#4586)
- Node docs (#4572)
- [SDK][API] Remove event key endpoint / client code (#4338)
- [backup] tf: add back backup intervals
- [consensus] support a recovery mode if consensusdb is gone
- [forge][telemetry] enable node telemetry in forge (#4490)
- [storage] rename target_snapshot_size (#4615)
- [txn-emitter] Fix computation for needed coin balance (#4614)
- [executor] fix integration test helper
- enable backup-cli unit tests in ci
- [gha] Make forge namespace optional
- [network] limit the max fragments in stream message
- [consensus] limit the payload size and remove unused quorum store variant
- [doc] update doc to remove test mode (#4626)
- [gha] Enable release on PR, enable HAProxy on release test
- [Aptos Stdlib] Make scaling factor actually useful in pool_u64
- [API Client] Fix wait_for_transaction to wait for expiry and return better messages (#4456)
- [Lint only] Fix docs lint
- [Vesting][Audit] Fix several minor issues in the vesting contract (#4560)
- [Audit][Aptos Framework][Staking contract] Zero out distribution pool when settling dust (#4585)
- [Token] Enfore no zero balance token
- [move] Do not include vector native implementations (#4621)
- [Stake] Validate lockup (#4632)
- [forge] fix max_block_txns rename (#4643)
- [move-examples] nft move example (#4512)
- [Staking] Move validator to pending_inactive instead of directly removing (#4633)
- [consensus] Remove skip_serializing_if from BlockRetreivalRequest (#4644)
- [telemetry] Send build info periodically
- [telemetry] Retry sending telemetry on transient errors
- [telemetry] Reset RUST_LOG_TELEMETRY to original value on unset
- [telemetry] send node config as event periodically
- Update connect-to-aptos-network.md
- [Config] Update disk size to 1000Gi. (#4622)
- Update API changelog
- [audit] timestamp.move (#4619)
- [cli] Increase REST endpoint timeout to 30s (#4628)
- [Token] reorgnize code
- [mempool] more/better metrics (#4616)
- [Prover spec only] Fix a typo in the bit_vector.move's prover specs (#4654)
- Fixed the spec in the stake module (#4656)
- [forge] Add tests for validation set changes (#4279)
- [Audit] Fix minor issues from audit
- Add complex token table indexing (#4324)
- added gas-estimation benchmarks for BLS12-381, Ed25519, secp256k1, Ristretto255 and cryptographic hash functions (#4630)
- [gas] initial gas parameters for table operations (#4659)
- [Token] Relax time constraint
- [Token] deprecate the token_coin_swap
- [Voting] Ensure proposal execution cannot happen in the same transaction as the last vote (#4612)
- [aggregator] Fix delta merging with history
- fixed a typo
- fixed ordering of delta merging
- fixed ordering of delta merging 2
- fixed a typo
- fixed naming
- changed names, used unwrap_or
- refactored code to remove duplication between match arms
- changed old names in macros
- [aptos-node] fixing the VM natives by excluding move-deps from the dependency tree (#4660)
- Revert "[HApropxy] new haproxy config and resources"
- [cli] Make faucet compatible with more faucet implementations
- [cached-packages] Update cached move packages
- [Execution][Fix] Do not panic when proof fetcher cannot send proof. (#4663)
- [rest-client] Change warn level message to debug for a transaction not being present
- [cli] Bump version to 0.3.7
- [genesis] Make is test optional as a layout field
- [cli] Fix genesis mainnet input to be a flag
- [genesis] Support mainnet genesis balance files
- [genesis] Fix employee map loading
- [genesis] Make a better message if a file isn't found
- [genesis] Check for accounts that aren't in the initial balances
- [genesis] Cleanup error messages to use enumerated for employee pools
- [genesis] Ensure vesting schedule adds up properly
- [genesis] Add more verification checks
- [genesis] Change genesis error output to be more helpful
- [genesis] Add more validations to validators
- [genesis] Check employee validators with other validators
- [genesis] Check total supply
- [genesis] Add total stake checks for employee accounts
- [genesis] Ensure full node host and validator host aren't the same
- [genesis] Fix tests for mainnet genesis
- [vm] Invalidate loader cache on any module bundle loading errors (#4668)
- [gas] storage_gas initial value fix (#4658)
- Validate string arguments to transaction
- Fix: typos
- [Trivial] Remove an used index variable
- [sdk-builder] Fix default sdk builder language
- change backup pod log level to info
- [aggregator] Fixed the description of sub()
- [Prover] fix the spec of `bit_vector::unset`
- [framework] eliminate front running of resource accounts
- [Docs] Adding sitemap option.
- [Docs] Consolidating all the troubleshooting sections into a new top-level doc.
- [Docs] Fixing index link.
- Make small direct edits
- Fix links to docs with .md extension and relative paths
- [test on forge] Add state sync catching up stress tests (#4036)
- [helm] redirect primary ingress (#4682)
- [helm][fullnode] option to load genesis from k8s secret (#4679)
- [api] Add git hash to index API
- [rosetta]  Split operator overriding function out
- [rosetta] Add error message for when max gas is too low
- [txn-emitter] fix mint and add transfer traffic (#4349)
- [audit] property_map.move (#4597)
- [prover] Update Boogie to 2.15.8 (#4671)
- [dashboards] sync grafana dashboards (#4550)
- chore: bump TS SDK version
- [backup] fix flaky test_save_list_metadata_files
- [move] Upgrade move version to include runtime checks (#4547)
- [haproxy] haproxy config and resources v3
- Add docgen-ready comments to `storage_gas.move` (#4699)
- [bcs] switch version
- Update to debian:bullseye-20220912 in our Rust images Dockerfile (#4344)
- [cli] Add typeargs for script support and move example (#4669)
- [Coverage] Fix ignore path (#4177)
- [CLI] Allow args to contain colons (#4706)
- [dev_setup] Add unzip to another path in dev setup script
- [prometheus] remove aptos-procs job for k8s pod discovery (#4495)
- [genesis] Check that root key isn't set for mainnet
- [genesis] Add eprintln for file that is currently being read
- [types] Add a more explicit input checker type AccountAddressWithChecks
- [genesis] More checks
- [genesis] Even more checks
- [genesis] Add more explicit checks for crypto keys
- [genesis] Fix messaging for balances.yaml file missing accounts
- [genesis] Print out all errors at the same time
- [genesis] Fix mainnet tests
- [serde] apply stricter recursion limit on user input
- [TS][SDK] Add ability to build FaucetClient with auth token (#4692)
- [gha] remove external pushgateway reference (#4707)
- Revert "[haproxy] haproxy config and resources v3" (#4719)
- [dashboards] sync grafana dashboards (#4695)
- Update connect-to-aptos-network.md
- [types] fix feature flags for itertools (#4684)
- [backup] fix flaky test utils::stream::futures_unordered_x::tests
- [Genesis] Move previously hardcoded vesting configurations into genesis configurations (#4718)
- Revert "Revert "[haproxy] haproxy config and resources v3" (#4719)" (#4723)
- [Compression] Enforce size limit before compression (#4708)
- Add auth token to TS tests / examples to bypass devnet tap ratelimits (#4716)
- Update connect-to-aptos-network.md
- Update connect-to-aptos-network.md
- Add gas documentation (#4680)
- Fix spelling error
- Incorporate How Base Gas Works doc into dev site
- lookup table handle in collection table when missing from txn (#4702)
- Adding haproxy to fullnode docker compose

### Description

### Test Plan

2022-10-03 22:57 UTC, perryjrandall commented
1) There are some unrelated changes in here that need testing and more explanation
2) In either case you need a test plan for this

2022-10-03 22:57 UTC, perryjrandall requested changes
Please show how you tested this

2022-10-04 08:19 UTC, Markuze commented
A. docker haproxy.cfg is aligned with terraform haproxy.cfg.
B. Tested on my aws ubuntu VM:
        docker compose -f  <filename> up

2022-10-11 00:38 UTC, perryjrandall approved these changes

2022-10-17 11:20 UTC, closed without merging