[haproxy] Add runtime socket and simple transaction caching for fn
aptos-labs/aptos-core pull request #5091
Opened 2022-10-17 07:41 UTC by perryjrandall

Add runtime socket to do all kinds of fun things like inspect / modify process
state and advanced debugging.

More info here: https://www.haproxy.com/blog/dynamic-configuration-haproxy-runtime-api/

Enable caching of transactions, this is especially useful for loading things
like the genesis blob which we can easily store and serve from memory.

This is intended to try and take just a little load off our fullnodes and it is
safely cacheable since transactions are immutable.

Test Plan: running docker compose locally of a fullnode connected to devnet

https://aptos.dev/nodes/full-node/fullnode-source-code-or-docker/#approach-2-using-docker

Add config, curl, time and check cache contents to make sure caching only
happen on endpoint we expect

```
mkdir ~/fullnode

cp all files over from src dir
mkdir keys
echo > keys/validator-full-node-identity.yaml

docker compose up -d

curl localhost:8080/v1/
{"chain_id":34,"epoch":"42","ledger_version":"5925004","oldest_ledger_version":"0","ledger_timestamp":"1665991966714301","node_role":"full_node","oldest_block_height":"0","block_height":"2339367"}%

echo "show cache" | docker run -i -v /Users/perry/fullnode/haproxy.sock:/var/run/haproxy.sock alpine/socat stdio /var/run/haproxy.sock
0xffff8b9ff03a: apicache (shctx:0xffff8b9ff000, available blocks:131072)

time (for i in {1..100}; do (curl localhost:8080/v1/transactions/by_version/0 &>/dev/null) || echo failed; done)
( for i in {1..100}; do; ( curl localhost:8080/v1/transactions/by_version/0 &)  0.33s user 0.63s system 15% cpu 6.123 total

echo "show cache" | docker run -i -v /Users/perry/fullnode/haproxy.sock:/var/run/haproxy.sock alpine/socat stdio /var/run/haproxy.sock

0xffff8b9ff03a: apicache (shctx:0xffff8b9ff000, available blocks:131072)
0xffff8b9ff0c0 hash:3974537210 size:2126450 (2077 blocks), refcount:0, expire:290
```

2022-10-17 11:20 UTC, Markuze approved these changes

2022-10-17 14:12 UTC, banool requested changes
Could you explain the transaction caching behaviour further? There are off the top of my head a few distinct ways the transactions endpoints are not immutable:
1. A single transaction is itself not immutable until it has been committed (success or failure) or rejected. Caching the response from checking a transaction could lead a client to wait forever, as currently they poll to wait for a transaction to be committee / rejected.
2. Transactions can be pruned, the cache could delay knowledge that this happened.
3. Even if transaction responses were immutable, the response of the '/transactions` endpoint changes bc it uses paging of the n most recent transactions. 

I feel I don't quite understand what is being cached here though. Is it caching the response based on an identical request, where identical means same path, method, query params, etc?

Also could you confirm that this only affects `/transactions` itself or anything with that as the start of the path?

2022-11-05 20:15 UTC, davidiw commented
gonna close this out as stale...

2022-11-05 20:15 UTC, closed without merging

2022-11-05 20:15 UTC, davidiw commented
I agree with @banool , naive caching won't work here... we need a relatively smart cache or we risk harming the ecosystem.