[Dockerfile] validator testing for bcc
aptos-labs/aptos-core pull request #5573
Opened 2022-11-15 12:54 UTC by Markuze

### Description

### Test Plan

2022-12-01 22:24 UTC, msmouse approved these changes

2022-12-01 22:41 UTC, rustielin requested changes
Can we keep these extra tools in the `validator-testing` image and not the primary public `validator` image? Our images are getting real bloated, and looking at the latest builds off your PR, this PR makes it 2x (to 2600 MiB). Also the included headers are amazon-specific. Seems too specific to our own setup to include in the public image

Is there another way we can get these tools into the env without baking it into the image?

2022-12-02 14:32 UTC, Markuze commented
@rustielin moved everything to validator-test; the kernel headers are specific for a reason.
Please re-review

2022-12-02 19:44 UTC, igor-aptos approved these changes

2022-12-02 19:58 UTC, merged

2022-12-02 22:31 UTC, sitalkedia commented
@Markuze - Can you clarify if this is default for all Forge runs on not?