[replay-verify] Add an option to skip txns that are known to broke backward compatibility
aptos-labs/aptos-core pull request #5747
Opened 2022-12-01 18:18 UTC by runtian-zhou

### Description

Add an option to intentionally skip re-execution for txns that broke backwards compatibility

### Test Plan

TBD

2022-12-01 18:19 UTC, runtian-zhou commented on storage/backup/backup-cli/src/backup_types/transaction/restore.rs
> +                info!("{:?} {:?} {:?}", first_version, idx, self.txns_to_skip);
Versions here don't seem to match with the version from the chunk_replayer

2022-12-07 19:38 UTC, msmouse approved these changes

2022-12-07 19:38 UTC, msmouse commented on storage/backup/backup-cli/src/backup_types/transaction/restore.rs
> +                let chunk_begin_version = chunk_replayer.current_committed_version().unwrap();
the problem is the version you get here is not the same as when the async closure is actually ran (later).

2022-12-07 19:39 UTC, msmouse requested changes

2022-12-07 19:39 UTC, msmouse commented on storage/backup/backup-cli/src/backup_types/transaction/restore.rs
> +                let chunk_begin_version = chunk_replayer.current_committed_version().unwrap();
Proly move the logic into the closure, or let chunk_replayer take the entire lookup table.

2022-12-07 21:18 UTC, msmouse approved these changes

2022-12-08 20:24 UTC, merged