[TS SDK] Remove SDK release steps from SDK CI
aptos-labs/aptos-core pull request #6741
Opened 2023-02-22 23:59 UTC by 0xmaayan

### Description

https://github.com/aptos-labs/aptos-core/issues/6707

### Test Plan

2023-02-23 10:42 UTC, banool requested changes
Requesting changes based on the change to docker-build-test.yaml. Once that's addressed, the rest of this looks good!

2023-02-23 10:42 UTC, banool commented on .github/workflows/docker-build-test.yaml
> +  pull_request:
I figure you don't mean to land this, and this change was just for testing?

2023-02-23 17:42 UTC, banool approved these changes
Looks great!!

2023-02-24 02:13 UTC, 0xZihan approved these changes

2023-02-24 02:13 UTC, merged