Use aptos_account::transfer_coins by default in Python SDK
aptos-labs/aptos-core pull request #6949
Opened 2023-03-06 19:00 UTC by banool

### Description

### Test Plan

2023-03-06 19:06 UTC, movekevin approved these changes

2023-03-06 20:04 UTC, gregnazario requested changes
Blocked until framework is updated in Mainnet

2023-03-24 15:31 UTC, closed without merging

2023-03-24 15:32 UTC, davidiw commented
I guess this was done somewhere else?

2023-03-25 15:28 UTC, banool commented
Hmmm yeah looks like it, must've been part of @movekevin's PR.