[Stroage] Delete stale state values and merkle nodes at version 0 after fast sync.
aptos-labs/aptos-core pull request #7007
Opened 2023-03-08 21:25 UTC by grao1991

### Description

### Test Plan

2023-03-08 21:58 UTC, msmouse approved these changes
Deleting the genesis is really messy from the first place. We should really try to fast sync to an empty DB instead.. 
cc @JoshLind

2023-03-08 23:51 UTC, msmouse commented
Okay, guess we need to talk with @JoshLind  to see if we can make the right way -- start fast syncing to an empty DB in the first place

2023-03-09 03:12 UTC, grao1991 commented on storage/aptosdb/src/lib.rs
> +        let node_key_at_fast_sync_version =
The previous logic has some issues.. updated now.

2023-03-09 19:00 UTC, areshand commented on storage/aptosdb/src/lib.rs
> +            if version != 0
would be great to add some documentation on the reasoning of having this condition?
My understanding is:
version != 0 seems to indicate the node value has been updated after fast_sync version
version == 0 means the value hasn't been updated. 
why do we only want to delete the nodes in one scenario?

2023-07-02 02:45 UTC, davidiw approved these changes

2023-08-26 22:58 UTC, davidiw requested changes
we can't leave approved PRs open this long...

2023-08-26 22:58 UTC, closed without merging