Add dashboard.stakeaptos.com and postman collection to community contributions
aptos-labs/aptos-core pull request #7044
Opened 2023-03-10 01:51 UTC by pakaplace

### Description
Adding the validator dashboard (dashboard.stakeaptos.com ) and postman collection our Paymagic team made.

2023-03-10 19:30 UTC, clay-aptos requested changes
Thanks for the contribution, Parker. Since this is external to Aptos.dev, it should actually land in this list (at the top as latest):
https://aptos.dev/community/external-resources

By editing:
https://github.com/aptos-labs/aptos-core/blob/main/developer-docs-site/docs/community/external-resources.md

Still, I see the following error when trying toggling from one network to another after loading an example:
`Error - Validator not found at that address. Check your selected nework and address`

Can we resolve that too? Thanks!

2023-03-15 02:58 UTC, pakaplace commented
Hi @clay-aptos , I moved it to external resources and I fixed the previewnet example bug. Our RPC endpoint was screwed up when you tested it, although the mainnet example never broke. It's ready for review, thanks.

2023-03-15 14:41 UTC, clay-aptos approved these changes

2023-03-15 15:43 UTC, michelle-aptos approved these changes

2023-03-16 15:12 UTC, clay-aptos commented
I resolved the merge conflict and added Paymagic to the spellcheck list in:
https://github.com/aptos-labs/aptos-core/pull/7203

Asking @michelle-aptos and @saharct to review and approve that.

2023-03-16 15:14 UTC, michelle-aptos approved these changes

2023-03-16 23:25 UTC, merged