Add Ansible Playbook for node management (docker)
aptos-labs/aptos-core pull request #7111
Opened 2023-03-14 01:10 UTC by dylanschultzie

### Description

Ansible playbook for Aptos public nodes. This playbook is intended for node runners who utilize docker, however it does also install aptos cli for those who may want it installed. Note also it makes no assumptions about how many resources should be allocated to docker - it'll eat as much as it wants. This is not intended to be used to fully setup a validator or full node, but to help initiate the process.

This repo contains 2 playbooks:
1. full public node setup (install docker, dependencies, download config files, begin sync process)
2. manage network upgrades to latest version

### Test Plan

2023-03-14 02:23 UTC, sherry-x approved these changes
Super cool, thank you!

2023-03-14 14:23 UTC, clay-aptos requested changes
This looks good except we are missing the Author column it seems. See your other PR for a working example:
https://github.com/aptos-labs/aptos-core/pull/7052

2023-03-14 20:19 UTC, michelle-aptos approved these changes

2023-03-16 03:18 UTC, saharct approved these changes
A great addition!

2023-03-16 04:23 UTC, merged