Link to petra.app from Create and Fund Accounts for guidance on obtai…
aptos-labs/aptos-core pull request #7470
Opened 2023-03-29 17:19 UTC by clay-aptos

…ning private key

### Description

### Test Plan

2023-03-29 19:38 UTC, saharct approved these changes

2023-04-02 22:21 UTC, davidiw requested changes
Feel free to dismiss changes if others feel strongly about this...

2023-04-02 22:21 UTC, davidiw commented on developer-docs-site/docs/guides/get-test-funds.md
> +  * Enter an existing private key, for example [found in your wallet](https://petra.app/docs/use).
This link isn't particularly great. It drops users off in a massive page far from the actual content. I also don't think that users will need this level of guidance. If they do, we probably shouldn't be advising them without more around private key management.

2023-04-19 15:43 UTC, davidiw commented
This is talks about creating a new account, so the additional guidance is misleading.

2023-04-19 15:43 UTC, closed without merging