[rosetta] Add lockup_expiration to account balance metadata
aptos-labs/aptos-core pull request #7711
Opened 2023-04-12 19:12 UTC by supriyam9

### Description

### Test Plan

2023-04-12 21:39 UTC, gregnazario requested changes

2023-04-12 21:39 UTC, gregnazario commented on crates/aptos-rosetta/src/types/requests.rs
> +    pub lockup_expiration_time_utc: Option<DateTime<Utc>>,
Let's leave this as u64 seconds, and let you interpret it on the client side.

These tend to convert time into weird formats.

2023-04-12 21:39 UTC, gregnazario commented on crates/aptos-rosetta/src/types/misc.rs
> +}
We can drop all this

2023-04-13 00:03 UTC, gregnazario approved these changes

2023-04-13 16:28 UTC, 0xmaayan approved these changes

2023-04-13 16:52 UTC, banool approved these changes

2023-04-13 17:00 UTC, merged