add x-aptos-client header
aptos-labs/aptos-core pull request #7822
Opened 2023-04-18 15:59 UTC by 0xmaayan

### Description

### Test Plan

2023-04-19 17:11 UTC, 0xjinn commented
Shall we do a manual test against the aptos explorer?

2023-04-19 17:12 UTC, 0xjinn approved these changes

2023-04-19 21:15 UTC, gregnazario approved these changes

2023-04-19 22:41 UTC, banool commented
We cannot release this feature until the API side change (https://github.com/aptos-labs/aptos-core/pull/7797) rolls out to all devnet, testnet, and mainnet fullnodes. Even then we should let it bake for a bit to ensure all community fullnodes have updated. If a client with the change in this (7822) PR tries to talk to an API without the change from #7797, it will fail because the CORS policy does not allow the new header.

2023-04-25 21:58 UTC, gregnazario requested changes
Blocked on CORS updates

2023-05-23 22:50 UTC, banool approved these changes

2023-05-23 23:19 UTC, merged