[Spec] update specs of voting, transaction_fee, code
aptos-labs/aptos-core pull request #8172
Opened 2023-05-12 08:35 UTC by xudon9

### Description
This is a part of spec work for Aptos Framework from MoveBit. The changes are:
- Completed all specs left as TODO in `transaction_fee` and `voting`;
- Some functions in `code` gets specified.
### Test Plan
`aptos move prove -f voting.move`
`aptos move prove -f transaction_fee.move`
`aptos move prove -f code.move`

2023-05-12 23:58 UTC, rahxephon89 requested changes

2023-05-12 23:58 UTC, rahxephon89 commented on aptos-move/framework/aptos-framework/sources/voting.move
> +
Using assume with ghost state is not an ideal way to specify aborts_if condition. Could you try to write a spec fun version of get_proposal_state instead? If it is difficult to do so, we can visit this aborts_if condition later.

2023-05-12 23:58 UTC, rahxephon89 commented on aptos-move/framework/aptos-framework/sources/voting.move
> +
Same as above

2023-05-18 08:28 UTC, UIZorrot reviewed
We have fixed it on the newest commit

2023-05-25 05:18 UTC, junkil-park commented on aptos-move/framework/aptos-framework/sources/voting.spec.move
> +
remove the trailing whitespaces.

2023-05-25 05:19 UTC, junkil-park commented on aptos-move/framework/aptos-framework/sources/voting.spec.move
>          // Any way to specify the result?
what does this mean?

2023-05-25 05:19 UTC, junkil-park approved these changes

2023-05-27 07:42 UTC, rahxephon89 approved these changes

2023-06-14 12:08 UTC, merged