add voting::is_proposal_id_assigned
aptos-labs/aptos-core pull request #8184
Opened 2023-05-13 23:05 UTC by hamdiallam

### Description

voting.move aborts on invalid proposal ids. In order for our governance module to present a cleaner error, a view function on assigned proposal ids would be useful

### Test Plan

n/a as this is simply a view function addition.

2023-05-13 23:21 UTC, movekevin submitted a review, later dismissed
Why did boogie.bpl change so much?

2023-05-13 23:21 UTC, movekevin commented on aptos-move/framework/aptos-framework/sources/voting.move
> +    public fun is_proposal_id_assigned<ProposalType: store>(voting_forum_address: address, proposal_id: u64): bool acquires VotingForum {
nit: Rename this as proposal_exists

2023-05-13 23:34 UTC, hamdiallam commented on aptos-move/framework/aptos-framework/sources/voting.move
> +    public fun is_proposal_id_assigned<ProposalType: store>(voting_forum_address: address, proposal_id: u64): bool acquires VotingForum {
will do

2023-05-13 23:34 UTC, hamdiallam commented
> Why did boogie.bpl change so much?

Hm, i'm not sure but the additions look normal? I simply ran `cargo build -p aptos-cached-packages` after making the changes

2023-05-13 23:43 UTC, movekevin commented
> > Why did boogie.bpl change so much?
> 
> Hm, i'm not sure but the additions look normal? I simply ran `cargo build -p aptos-cached-packages` after making the changes

cc @rahxephon89 Do you know why boogie.bpl would change so much? This PR somehow generates 193,163 additions into that file

2023-05-15 00:26 UTC, rahxephon89 commented
I don't think boogie.bpl should be added to the repo in the first place. @hamdiallam @movekevin

2023-05-15 00:27 UTC, rahxephon89 commented on aptos-move/framework/aptos-framework/boogie.bpl
I don't think it should be included in the PR.

2023-05-15 02:54 UTC, hamdiallam commented on aptos-move/framework/aptos-framework/boogie.bpl
removed -- not sure where this came from

2023-05-23 04:31 UTC, hamdiallam commented
bump :) @movekevin @rahxephon89

2023-07-02 03:00 UTC, davidiw approved these changes

2023-07-02 17:24 UTC, movekevin approved these changes

2023-07-02 23:05 UTC, davidiw requested changes

2023-07-02 23:05 UTC, davidiw commented on aptos-move/framework/aptos-framework/sources/voting.spec.move
> +        include AbortsIfNotContainProposalID<ProposalType>;
this is wrong, your function cannot abort under these circumstances.

2023-08-05 22:30 UTC, davidiw commented
closing out, feel free to re-open when fixed / complete.

2023-08-05 22:30 UTC, closed without merging