[TF] More fixes for GCP DNS
aptos-labs/aptos-core pull request #8253
Opened 2023-05-17 20:07 UTC by sionescu

### Test Plan

Tested on the new GCP Devnet.

2023-05-17 20:36 UTC, rustielin approved these changes
do you also still need this https://github.com/aptos-labs/aptos-core/pull/8160 in conjunction with this PR?

2023-05-17 20:55 UTC, rustielin commented
@sionescu I think it makes sense in a world where we don't care about DNS but still want a testnet or single node. It's mostly for test cases, and also brings it up to parity to the AWS setup

2023-05-17 21:04 UTC, sionescu commented
@rustielin Yes, in that case let's merge #8160.

2023-05-19 23:00 UTC, sherry-x approved these changes

2023-05-31 21:20 UTC, rustielin requested changes

2023-05-31 21:20 UTC, rustielin commented on terraform/helm/testnet-addons/templates/ingress.yaml
> +    {{- if eq .Values.cloud "EKS" }}
nit: `aws` and `gcp` rather than `EKS` and `GKE`?

2023-06-05 22:53 UTC, rustielin approved these changes

2023-06-05 23:58 UTC, merged