reduce aptos-api error size
aptos-labs/aptos-core pull request #8265
Opened 2023-05-18 03:16 UTC by simonjiao

### Description

- Boxing api errors to reduce error size
- Relax version restrication for poem-openapi to fix compile error

### Test Plan
cargo build && cargo test

2023-05-18 10:03 UTC, banool requested changes
Hey thanks for this PR! 

The reason we pin the version is because future Poem versions change the content type string (from `application/json` to `application/json; charset: utf-8` and I don't want to invest the effort to figure out if this is a breaking change right now. Please find a way to resolve the compilation errors without relaxing the Poem version requirements if at all possible.

2023-05-19 04:51 UTC, simonjiao commented
> Hey thanks for this PR!
> 
> The reason we pin the version is because future Poem versions change the content type string (from `application/json` to `application/json; charset: utf-8` and I don't want to invest the effort to figure out if this is a breaking change right now. Please find a way to resolve the compilation errors without relaxing the Poem version requirements if at all possible.

sure. Will remove that changes.

2023-05-19 07:57 UTC, banool approved these changes
Thanks! Looks good to me now, let's see how it goes in CI.

2023-05-25 01:45 UTC, davidiw approved these changes

2023-05-30 04:12 UTC, merged