[framework][spec] Refactor the coin module to express total supply as a global invariant
aptos-labs/aptos-core pull request #8611
Opened 2023-06-10 10:16 UTC by rahxephon89

### Description

To specify the total supply property as a global invariant, this PR adds public friend functions `burn_internal`, `extract_internal`,  `merge_internal`, `extract_all_internal` and `mint_internal` and replaces public APIs with them in the aptos framework.

2023-06-11 21:27 UTC, movekevin reviewed
Would you mind elaborating more on why we need the friend-only internal versions of these functions (the description only says it's needed for total supply specification but doesn't explain why)? Looks like a decent amount of boilerplate code to me :)

2023-06-12 03:18 UTC, rahxephon89 commented
> Would you mind elaborating more on why we need the friend-only internal versions of these functions (the description only says it's needed for total supply specification but doesn't explain why)? Looks like a decent amount of boilerplate code to me :)

Sorry I did not clearly explain it. I have updated the description of this PR. Please let me know if there are any concerns with these changes.

2023-07-15 18:20 UTC, davidiw requested changes
Considering that calling functions is not free, it might be a better solution to update the move prover than coercing developers to pick up what looks like questionable programming paradigms.

2023-07-15 21:04 UTC, wrwg commented
> Considering that calling functions is not free, it might be a better solution to update the move prover than coercing developers to pick up what looks like questionable programming paradigms.

I disagree. The reason why this is refactored for the prover is not because the prover has a deficiency here, but simply because the semantics of the `foo` and `foo_internal` functions is different. The pre-conditions you can assume about those functions is different if they are public entry points vs if they are only called privately, which leads to different reasoning. The extra function call is minimal in gas cost IMO. Happy to discuss if you are not convinced. In general, it is very common in our verification effort that code may need to be rewritten a little for verifiability.

2023-07-15 21:26 UTC, davidiw commented
> 

Would love to learn more, I found this line:

> This would be legal only if `setup` is a private or `public (friend)` function. The difference between this and disabling invariants in `setup` is that the invariants would not be assumed at the beginning of `setup` and would be proved after `setup` returns at each site where it is called.

(From https://aptos.dev/move/prover/spec-lang#global-invariants)

Which seems to indicate that there's a nuance that the prover may not actually prove the following invariants inline but when proving the caller of this function?

Which makes me wonder... is it possible to then produce a private function that would prove the public function instead, something to the effect of

```
fun burn_for_prover(...) {
  burn(...)
```

and then prover could just prove that?

2023-07-16 02:31 UTC, wrwg commented
> > 
> 
> Would love to learn more, I found this line:
> 
> > This would be legal only if `setup` is a private or `public (friend)` function. The difference between this and disabling invariants in `setup` is that the invariants would not be assumed at the beginning of `setup` and would be proved after `setup` returns at each site where it is called.
> 
> (From https://aptos.dev/move/prover/spec-lang#global-invariants)
> 
> Which seems to indicate that there's a nuance that the prover may not actually prove the following invariants inline but when proving the caller of this function?

Yes, that is the effect of suspended invariants via `delegate_invariants_to_caller`.  However, we do not allow this pragma for public functions because they have unknown callers.

> 
> Which makes me wonder... is it possible to then produce a private function that would prove the public function instead, something to the effect of
> 
> ```
> fun burn_for_prover(...) {
>   burn(...)
> ```
> 
> and then prover could just prove that?

This unfortunately does not work, because what you are effectively are doing is to enforce that after you exit `burn`, whether called from inside the module or from outside, the invariants must hold. But the `delegate_invariants_to_caller` is transitive, and if the caller has the same attribute, the invariants will be postponed to its caller, and so on and so on.

That is why currently we simply disallow `delegate_invariants_to_caller` for public functions.

The alternative (and we had something like this implemented in earlier version of the Prover) would be to actually be able to reflect over from where a function is called. So effectively, there are two burn functions:

(a) the public one, which enforces invariants at exit
(b) the private one, which does not enforce them

Now you choose either the (a) or the (b) semantics depending on whether the next element on the caller stack is an external or internal function...

This is a terribly complicated model, and thats why we retired it. I hope you can see from this argument that independent of prover or not, it can be rather difficult to reason informally about such functions.

2023-07-27 21:31 UTC, rahxephon89 commented
> The alternative (and we had something like this implemented in earlier version of the Prover) would be to actually be able to reflect over from where a function is called. So effectively, there are two burn functions:
> 
> (a) the public one, which enforces invariants at exit (b) the private one, which does not enforce them
> 

Hi @wrwg, sorry for the stupid question again. If a function is already marked as public, can we just go to the case (a)? Then,  if a public function is called in a private function, we just check whether the assumption holds by an assertion before calling it and output verification error if it does not?

2023-07-29 00:31 UTC, rahxephon89 commented
Sorry for the delayed reply @davidiw and @wrwg. Here are some further and yet immature thoughts on this issue.

For public(friend) and private functions, the pragma `delegate_invariants_to_caller` can be used without any issues. For the public function, it is different because we do not know how it will be called and thus`delegate_invariants_to_caller` cannot be used. As a result, we introduce `disable_invariants_in_body`, another pragma for suspending the invariant check. With this pragma, we will assume the invariant at the entrance and then assert it at the exit of the function. If a function sets `disable_invariants_in_body`, then all its directly and indirect callees will turn-off invariant checking. Moreover, we have the following restrictions:

- invariant checking in an external facing function cannot be turned off, which means that public or script functions cannot be transitively called by functions disabling or delegating invariants;
- if a function is called (callee) in another function (caller) which has the pragma `disable_invariants_in_body` on, it means a suspendable invariant should not hold at any point in the function and thus the callee should not set the pragma `disable_invariants_in_body` .

And the restrictions above leads to code change in this PR:  the public function `on_new_epoch` in the `stake` module will call public APIs such as `mint`, `merge` or `extract_all` in the `coin` module. To prove a suspendable global invariant in `on_new_epoch` , the pragma `disable_invariants_in_body` is set. To prove some other global invariants in the `coin` module , `mint` and `merge` also have `disable_invariants_in_body` set, which causes the prover error.

I am wondering whether the current rules may be overly restrictive for public functions. In my opinion, for a public function, **no matter where it is called, all related global invariants must hold at both entrance and exit**. Thus, I am proposing that we relax the restrictions above and allow public functions to be called directly or indirectly by another function with `disable_invariants_in_body` being set. Then we insert assert before the call and assume after the call (for related global invariants) for them. If the prover outputs an verification error, it means the precondition is not strong enough and we may need to insert some spec blocks in the code to enhance the precondition.

2023-11-14 01:48 UTC, closed without merging