[Spec] update specs of aptos_governance
aptos-labs/aptos-core pull request #8657
Opened 2023-06-14 08:27 UTC by UIZorrot

### Description

This is a part of the spec work for Aptos Framework from MoveBit. The changes are:

Completed most of the TODO in `aptos_governance.move`

There are many changes in this PR.

### Test Plan

`aptos move prove -f aptos_gov`

2023-06-14 16:39 UTC, junkil-park commented on aptos-move/framework/aptos-framework/sources/aptos_governance.spec.move
> +        /// get_voting_power(stake_pool)
`///` --> `//` and could you give a bit more descriptive comment?

2023-06-14 16:41 UTC, junkil-park approved these changes
Thanks. The specs are very long. Could you use schemas to reduce the repeated spec as much as possible?

2023-06-15 22:09 UTC, rahxephon89 commented on aptos-move/framework/aptos-framework/sources/aptos_governance.spec.move
> +        // aborts_if simple_map::spec_contains_key(proposal.metadata, multi_step_in_execution_key) && !aptos_std::from_bcs::deserializable<vector<u8>>(b"true");
Do we need this commented-out aborts_if condition? If not, you can remove it

2023-06-16 00:21 UTC, rahxephon89 commented on aptos-move/framework/aptos-framework/sources/aptos_governance.spec.move
> +        include Schema_add_approved_script_hash;
Could you change the schema name to something like `SchemaAddApprovedScriptHash`?

2023-06-16 00:22 UTC, rahxephon89 commented on aptos-move/framework/aptos-framework/sources/aptos_governance.spec.move
> +        include Voting_Is_proposal_resolvable_Abortsif;
Same here, use upper camel case to rename the schema name.

2023-06-16 00:45 UTC, rahxephon89 requested changes
I am wondering whether the size of spec can be further reduced by introducing spec funcs for helper functions such get_voting_power.

2023-06-16 02:32 UTC, UIZorrot commented
> I am wondering whether the size of spec can be further reduced by introducing spec funcs for helper functions such get_voting_power.

Well, we believe it's hard to reduce the size by helper function, since using opaque on these function always bringing new "function does not abort" issues. The other problem is solved.

2023-06-16 06:00 UTC, rahxephon89 approved these changes

2023-06-16 06:40 UTC, merged