[DOC] Add `AptosToken` and `FungibleAssetClient` plugin classes to the doc site.
aptos-labs/aptos-core pull request #8779
Opened 2023-06-21 17:50 UTC by 0xmaayan

### Description
Add `AptosToken` and `FungibleAssetClient` plugin classes to the doc site.
### Test Plan

2023-06-21 20:26 UTC, gregnazario commented on developer-docs-site/scripts/additional_dict.txt
> +Transafer
Let's, not add `Transafer` to the dictionary, and instead of course use the word `Transfer`

2023-06-21 20:26 UTC, gregnazario commented on developer-docs-site/docs/sdks/ts-sdk/sdk-plugins-layer.md
> +- Unfreeze Token Transafer
Transfer

2023-06-21 20:26 UTC, gregnazario commented on developer-docs-site/docs/sdks/ts-sdk/sdk-plugins-layer.md
> +- Generate Transfer
What's generate transfer?

2023-06-21 20:43 UTC, 0xmaayan commented on developer-docs-site/docs/sdks/ts-sdk/sdk-plugins-layer.md
> +- Generate Transfer
generate transfer transaction https://github.com/aptos-labs/aptos-core/blob/main/ecosystem/typescript/sdk/src/plugins/fungible_asset_client.ts#L71

2023-06-22 10:34 UTC, saharct requested changes

2023-06-22 10:34 UTC, saharct commented on developer-docs-site/docs/sdks/ts-sdk/sdk-plugins-layer.md
> +The [AptosToken](https://github.com/aptos-labs/aptos-core/blob/main/ecosystem/typescript/sdk/src/plugins/aptos_token.ts) class compatible with the [token V2 standard](../../standards/aptos-token-v2.m
```suggestion
The [AptosToken](https://github.com/aptos-labs/aptos-core/blob/main/ecosystem/typescript/sdk/src/plugins/aptos_token.ts) class is compatible with the [token V2 standard](../../standards/aptos-token-v2.md) and provides methods for creating and querying NFT collections and tokens.
```

2023-06-22 10:34 UTC, saharct commented on developer-docs-site/docs/sdks/ts-sdk/sdk-plugins-layer.md
> +The [CoinClient](https://github.com/aptos-labs/aptos-core/blob/main/ecosystem/typescript/sdk/src/plugins/coin_client.ts) class provides methods to intercat with the coin module to transfer coins betw
```suggestion
The [CoinClient](https://github.com/aptos-labs/aptos-core/blob/main/ecosystem/typescript/sdk/src/plugins/coin_client.ts) class provides methods to interact with the coin module to transfer coins between accounts and to check an account balance. By default, it transfers `0x1::aptos_coin::AptosCoin`, but you can specify a different coin type with the `coinType` argument.
```

2023-06-22 10:34 UTC, saharct commented on developer-docs-site/docs/sdks/ts-sdk/sdk-plugins-layer.md
> +It covers (1) write methods that support creating a unique identity on the Aptos network by registering an Aptos name and (2) read methods to get an account ANS name by an account address and get an
```suggestion
It covers (1) write methods that support creating a unique identity on the Aptos network by registering an Aptos name and (2) read methods that retrieve an account's ANS name using its address, as well as retrieving an account's address using its ANS name.
```

2023-06-22 20:28 UTC, saharct approved these changes

2023-06-23 15:10 UTC, 0xjinn approved these changes

2023-06-23 15:10 UTC, merged