[dag] derive macro for message From impls
aptos-labs/aptos-core pull request #8855
Opened 2023-06-27 04:37 UTC by ibalajiarun

### Description

### Test Plan

2023-07-03 23:44 UTC, sasha8 approved these changes
Black magic. Can we add some tests?

2023-07-04 00:03 UTC, zekun000 requested changes
I think the idiomatic way is to derive based on the enum instead of individual struct, I'd imagine it's like
```
#[derive(EnumMessage)]
enum DAGMessage
```
and based on the internal struct to do dispatches

2023-07-04 19:23 UTC, ibalajiarun commented
> I think the idiomatic way is to derive based on the enum instead of individual struct, I'd imagine it's like
> 
> ```
> #[derive(EnumMessage)]
> enum DAGMessage
> ```
> 
> and based on the internal struct to do dispatches

yes, this is better. The only catch is all the structs should be in the same module as the enum right?

2023-07-04 19:32 UTC, zekun000 approved these changes
I think the types just need to be in the same crate not necessarily module (not foreign types), but I could be wrong. 

another nit: the name is not very representative, I'd call it EnumConversion. the same for the crate name, it's probably better to call it aptos-enum-conversion-derive

2023-07-04 23:02 UTC, zekun000 commented on crates/aptos-enum-conversion-derive/tests/cases/no_fields.rs
> +#[derive(EnumMessage)]
you need to update the tests lol

2023-07-04 23:19 UTC, ibalajiarun commented on crates/aptos-enum-conversion-derive/tests/cases/no_fields.rs
> +#[derive(EnumMessage)]
good catch.

2023-07-05 16:18 UTC, merged