[CICD] introduce kodiak merge queue
aptos-labs/aptos-core pull request #893
Opened 2022-05-10 09:21 UTC by geekflyer

2022-05-10 22:32 UTC, davidiw requested changes
As long as we require bors for performing tests and merging, this seems to add more quirks into the process. Perhaps internal-ops instead?

2022-05-10 22:32 UTC, davidiw commented on .kodiak.toml
> +method = "squash"
not all PRs have miscellaneous commits, this should ideally be a per PR decision.

2022-06-08 04:00 UTC, davidiw commented
what's the next steps here :)

2022-06-08 04:04 UTC, geekflyer commented
> what's the next steps here :)

i'm thinking about it as we speak - stay tuned :)

2022-06-15 05:45 UTC, davidiw commented
closing out per discussion.

2022-06-15 05:45 UTC, closed without merging