[Spec] Ensures of transaction_fee
aptos-labs/aptos-core pull request #9460
Opened 2023-08-03 14:59 UTC by UIZorrot

### Description

We have finished the remained post-condition in transaction_fee.move
As far as we know, all high-level spec is also complete

### Test Plan

aptos move prove -f transcation_fee

2023-08-07 00:07 UTC, rahxephon89 requested changes

2023-08-07 00:07 UTC, rahxephon89 commented on aptos-move/framework/aptos-framework/sources/transaction_fee.spec.move
> +            if (table::spec_contains(fees_table, proposer)) {
Could you also add the case where `prosper == @vm_reserved`?

2023-08-11 06:31 UTC, rahxephon89 approved these changes
LGTM, thanks!

2023-08-15 00:44 UTC, junkil-park approved these changes

2023-08-15 07:12 UTC, merged