[Spec] Ensures for voting
aptos-labs/aptos-core pull request #9462
Opened 2023-08-03 15:19 UTC by UIZorrot

### Description

We have finished the remained post-condition in voting.move.
As far as we know, high-level properties is all complete

### Test Plan

aptos move prove -f voting

2023-08-05 06:52 UTC, rahxephon89 requested changes
@UIZorrot I think `resolve_proposal_v2` will cause inconsistency issue. Could you use the flag  `--unconditional-abort-as-inconsistency` and `--check-inconsistency` to check whether there is an issue?

2023-08-11 06:04 UTC, UIZorrot commented
The inconsistency is coming from event.move, the latest updated fix the problem

2023-08-11 21:50 UTC, rahxephon89 requested changes

2023-08-15 16:42 UTC, junkil-park commented on aptos-move/framework/aptos-framework/sources/voting.spec.move
> -        ensures global<VotingForum<ProposalType>>(voting_forum_address).next_proposal_id
Why are these removed?

2023-08-16 09:09 UTC, rahxephon89 commented on aptos-move/framework/aptos-framework/sources/voting.spec.move
> -        ensures global<VotingForum<ProposalType>>(voting_forum_address).next_proposal_id
They are moved to the schema below

2023-08-21 08:04 UTC, rahxephon89 requested changes

2023-08-21 08:35 UTC, UIZorrot commented on aptos-move/framework/aptos-framework/sources/voting.spec.move
> +        aborts_if len(next_execution_hash) == 0 && is_multi_step && simple_map::spec_contains_key(proposal.metadata, multi_step_in_execution_key);
oh yes, i think you are right

2023-08-21 16:21 UTC, rahxephon89 approved these changes

2023-08-22 01:03 UTC, junkil-park approved these changes

2023-08-22 01:59 UTC, merged