Feat/pypi ci
aptos-labs/aptos-core pull request #9512
Opened 2023-08-06 12:10 UTC by zhenfeng-zhu

### Description

### Test Plan

2023-08-07 17:45 UTC, gedigi approved these changes

2023-08-08 17:52 UTC, banool requested changes
Thanks for the PR! Requesting changes for the workflow trigger.

2023-08-08 17:52 UTC, banool commented on .github/workflows/python_sdk_publish.yaml
> +on:
I don't think our current Python SDK testing process is strict enough for this to run on every push right now. Could we make this work on workflow_dispatch instead for now?

2023-08-08 17:52 UTC, banool commented on .github/workflows/python_sdk_publish.yaml
> +
Ideally we would also check that there is an entry in the CHANGELOG for this new version.

2023-08-08 17:54 UTC, banool commented on .github/workflows/python_sdk_publish.yaml
> +          curl -sSL https://install.python-poetry.org | python - -y
Let's use `actions/python-setup/action.yaml` instead, it sets up the correct Python version as configured in the repo, installs Poetry, etc.

2023-08-11 16:43 UTC, zhenfeng-zhu commented
Thanks for all your help, I have resolved some comment. Please review it!

2023-08-14 20:36 UTC, rustielin requested changes

2023-08-14 20:36 UTC, rustielin commented on .github/workflows/python-sdk-publish.yaml
> +  push:
we don't need the `push` trigger, can we just do it for `workflow_dispatch`?

2023-08-14 20:36 UTC, rustielin commented on .github/workflows/python-sdk-publish.yaml
> +          [[ "$(poetry version --short)" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] && [[ $(grep $(poetry version --short) CHANGELOG.md) =~ $(poetry version --short)  ]] || echo prerelease=true >> $GITHUB_OUTPUT
where is this github output being used?

2023-08-22 22:28 UTC, banool approved these changes
Looks good, thanks for changing to workflow_dispatch!!

2023-08-22 23:41 UTC, sionescu approved these changes

2023-08-23 18:15 UTC, merged