Update package-upgrades.md
aptos-labs/aptos-core pull request #9567
Opened 2023-08-09 12:06 UTC by cryptomolot

space added

2023-08-10 19:31 UTC, saharct approved these changes

2023-08-12 19:26 UTC, davidiw requested changes
going to fix this, but the original form was more accurate.

2023-08-12 19:26 UTC, davidiw commented on developer-docs-site/docs/move/book/package-upgrades.md
> +- Public (friend) functions are treated as private and thus their signature can arbitrarily change. This is safe as
```suggestion
- `public(friend)` functions are treated as private and thus their signature can arbitrarily change. This is safe as
```

2023-08-12 19:27 UTC, davidiw approved these changes

2023-08-12 19:28 UTC, merged